- packages/devtools-launchpad/src/components/LandingPage.css
The current footer of the landing page is too big and makes it hard to use when there are many tabs.
Before: 
After
> use smaller footer for landing page

- packages/devtools-launchpad/src/components/LandingPage.js
- packages/devtools-launchpad/src/components/LaunchpadApp.js
- packages/devtools-launchpad/stories/index.js
Pass the actual onClick handler as a props from LaunchpadApp to LandingPage so the current behavior
still works.
In storybook, when creating the LandingPage, pass an action logger so we don't have story inception anymore
Fixes #29
> Fix tab click in launchpad storybook

- packages/devtools-launchpad/src/components/LandingPage.css
- packages/devtools-launchpad/src/components/LandingPage.js
- packages/devtools-launchpad/stories/index.js
Add autoFocus on filter tab to make it faster to search for a specific tab.
Add tabIndex and :focus styling  on the relevant items (sidebar items, tab items) to make it easy to navigate with the keyboard in the app.
If there is only one tab (either because there is really only one, or because we filtered them out, pressing
<kbd>Enter</kbd> starts the debugging on the tab.
I'm not sure about https://github.com/devtools-html/devtools-core/commit/761e75789efcdd796bc86862a0944a7b3963c871 , which automatically focus the filter bar when clicking on a sidebar element, tell me what you think about this @jasonLaster & @juliandescottes 
Here's how keyboard navigation looks : 
And navigationg when there is only one tab :
> Better keyboard navigation

- packages/devtools-launchpad/webpack.config.js
cf. https://github.com/devtools-html/debugger.html/pull/1445#issuecomment-269310411 
If a tool using launchpad is requiring css files from several bundles, only one styles.css will be created, containing the CSS files from the last entry that got loaded.
I think we should both
* allow tools to provide an exclude regexp, to avoid including unnecessary styles in the bundle
* add the bundle name to the styles bundle, to avoid losing time investigating this kind of issues
cc @jasonLaster
> Multiple style bundles

- lerna.json
The lerna version was updated in commit 9f1429d857af014aa5f0c0e7dd717698f0f69d8e however the lerna configuration was not updated. This makes it fail when re-running the bootstrap process. This patch addresses the problem by updating the lerna config to use the currently depended upon version.
> Fix lerna version in config.

- packages/devtools-launchpad/src/components/LandingPage.js
The current line length for 19 is over 80 chars causing the pre-commit linting to fail. A quick reformat of the anchor creation fixes this so linting passes without issue.
> Fix line length so linting passes.

- packages/devtools-launchpad/src/lib/themes/dark-theme.css
Fixing this issue https://github.com/devtools-html/debugger.html/issues/1622
before focused
before unfocused
after focused or unfocused
I think both focused or unfocused should be the same
>   [DarkMode] fix text selection #1622 from debugger.html

- packages/devtools-launchpad/bin/development-server.js
- packages/devtools-launchpad/index.html
- packages/devtools-launchpad/webpack.config.devtools.js
- packages/devtools-launchpad/webpack.config.js
* switch to using an implicit bundleName over just using "bundle" or passing in an explicit one
* drop library name 
* cleanup some code
> Cleanup build options

- packages/devtools-launchpad/webpack.config.js
Fix for #69 
With this simple change I am able to use linking for all devtools-core packages with the debugger.
In the long run,  webpack2 should also improve the situation here.
Please note that when using linking, the "debugger.js" bundle goes from ~700 files to ~1200 files.
cc @jasonLaster
> support linking for all devtools-* modules

- packages/devtools-launchpad/src/components/LandingPage.css
The tab filter background wasn't set so it remained white. It now respects the theme and the text color was set to match the colors used in the EditorSearch in the debugger.
Screenshot
> Fix tab filter background and text color

- packages/devtools-modules/client/shared/components/splitter/SplitBox.js
To get this [issue](https://github.com/devtools-html/debugger.html/issues/1537) finished we needed some additional work in the SplitBox.
This change makes it so that based on the collapse state of the opposite pane the height of the uncollapsed will expand to the maximum allowed height.
> Modify the pane styles to properly collapse vertical SplitBox.

- packages/devtools-modules/client/shared/components/splitter/SplitBox.js
In split box, we calculate screenX and screenY with a consideration of the window's border. This is done by comparing window.outerWidth and window.innerWidth (or height).
When there are panels (e.g. devtools :) or bookmarks) the difference between outer and inner size is very large. So the split box breaks.
Neglecting the window's border is a small price to pay since it's around 5px (in Windows) compared to not being about to dock right (or dock bottom with a vertical flow).
The ideal solution would be to not use screenX and screenY, but I realize the tradeoff with not having to calculate relative coordinates of iframes.
> fix wrong calculation when panels are open

- packages/devtools-client-adapters/src/firefox.js
- packages/devtools-launchpad/webpack.config.devtools.js
- packages/devtools-launchpad/webpack.config.js
This should fix the issues mentioned in https://github.com/devtools-html/devtools-reps/issues/43
The webpack config now explicitly excludes all devtools-core module (except for launchpad & client-adapters, which were "unexcluded" afterwards).
Also fixed a small bug with the ff client adapters which makes the actions argument of the launchpad bootstrap method mandatory, while reps is not providing any action.
> Fix devtools-core for reps (linking & ff client)

- packages/devtools-launchpad/webpack.config.devtools.js
I missed this while testing the later externalsRequire patch.
The issue is that `[0]` gets the first character of the mapping.
> fix externals require mapping

- packages/devtools-launchpad/src/components/Root.js
- packages/devtools-launchpad/src/index.js
Related to the memory leak we found yesterday, I think it makes sense to leave the responsibility to launchpad to unmount the proper node, since launchpad is the one that decides to create a child in #mount.
> add unmountRoot in devtools-launchpad

- packages/devtools-launchpad/src/tools/mc/make-bundle.js
There's a strange race condition with `process.env.TARGET`, which causes the wrong config to be used.
CC @juliandescottes
> fix process race condition

- packages/devtools-launchpad/README.md
- packages/devtools-launchpad/package.json
I might be the only one going to https://www.npmjs.com/package/devtools-launchpad but some of the links still point to debugger.html and the image is an issue.
> Cleanup for https://www.npmjs.com/package/devtools-launchpad

- packages/devtools-launchpad/package.json
npm needed a version bump to take changes from https://github.com/devtools-html/devtools-core/pull/124 into account
> Version bump to be able to publish readme changes on npm

- packages/devtools-launchpad/bin/firefox-proxy
This is an outstanding issue 1782 in repo:
https://github.com/debugger-tools/debugger-html.git
This is an example for a meetup so people can see the whole contribution
cycle via, forking and creating pull requests using up-for-grabs issues.
> condensing output from log on yarn run command to save space

- packages/devtools-client-adapters/src/chrome.js
- packages/devtools-client-adapters/src/chrome/events.js
Associate issue #168
- Select chrome as the debuggee
- Set breakpoints in the `willNavigate()` and `navigated()` actions
- Go back and forward using the using the back and forward buttons in chrome
- Watch for the breakpoints hit
> Fix to enable tracking of navigation events in chrome

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/index.js
- packages/devtools-launchpad/webpack.config.devtools.js
- packages/devtools-launchpad/webpack.config.js
- packages/devtools-launchpad/yarn.lock
This removes the need for SMP, which was keeping us from using `babel-traverse`.
SMP was needed before because it helps deal with duplicate versions of `devtools-config` or `react`. If we take on the responsibility of making sure that we don't do this, we are okay.
I tested this version in the debugger and hot reloading worked.
> Drop SingleModulePlugin

- package.json
Addresses #182
Destroys the `node_modules` directories to reset in case of errors
Works on Mac and Windows (with GitHub Git Shell)
> rm -r node modules

- packages/devtools-launchpad/src/tools/mc/make-bundle.js
- packages/devtools-launchpad/src/tools/mc/symlink-tests.js
Two changes for tools in devtools-core:
- forward error messages when make-bundle rejects
- support custom paths in symlink test
Can split the PR in two, I guess the second proposed change can be a bit divisive.
> Tools fixes

- bin/install-yarn
- circle.yml
CircleCI updated their yarn docs https://circleci.com/docs/yarn/
If we don't care as much about the yarn version as we used to, and I don't think we do, then we can use a much simpler setup that uses the latest available yarn.
> update the circleci config and remove yarn-install script

- packages/devtools-launchpad/bin/development-server.js
Disable chunk logs from webpack.
> Suppress chunk logs of webpack

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/yarn.lock
This increments `postcss-bidirection` version to `2.0.3`. [postcss-bidirection/CHANGELOG.md](https://github.com/gasolin/postcss-bidirection/blob/master/CHANGELOG.md)
:warning: I haven't checked this after linking. I modified `yarn.lock` file in `debugger.html` [https://github.com/devtools-html/debugger.html/blob/master/yarn.lock#L1887](https://github.com/devtools-html/debugger.html/blob/master/yarn.lock#L1887) to verify that this will solve the issues.
Here is a screenshot of RTL with this version.
This also fixes devtools-html/debugger.html#2042 devtools-html/debugger.html#2056 And partially devtools-html/debugger.html#2041
> Increment postcss-bidirection to fix RTL issue

- packages/devtools-launchpad/package.json
Because we use Yarn in the prepublish step, it's important to control the
version we use. As a nice side-effect, `npm install` now works even on systems
where Yarn isn't installed globally.
> Add Yarn as a dev dependency

- packages/devtools-launchpad/package.json
This prevented npm install from working in debugger.html.
> Fix wrong path to development-server.js in package.json

- packages/devtools-sham-modules/shared/client/main.js
dropped some hungarian notation and restyled the file.
> reformat main

- packages/devtools-client-adapters/src/firefox/create.js
When the debugger is already paused, the packet does not have a frame
> Fix error when already paused

- packages/devtools-launchpad/src/components/Root.css
Firefox uses 13.33333px default on my system
Chrome uses 16px.
This forces both to use 14 (which I took from Atom/VS Code as their default size). 🤷‍♂️
> Set the root font-size to force a consistent size between firefox/chrome/etc

- packages/devtools-launchpad/src/components/Root.css
This caused some components to have 14px font sizes.
> Revert 14px font sizes

- packages/devtools-launchpad/src/index.js
Clearing firefox tabs before getting new tabs was causing flicker.
* Clear firefox tabs after getting new tabs. So that there is no noticeable delay between clearing tabs and displaying new tabs.
Fixes #229
> [launchpad] Clear firefox tabs after getting new tabs

- packages/devtools-launchpad/src/lib/themes/common.css
This sets a consistent root font size between chrome and firefox
> Set root font-size to 11px

- packages/devtools-launchpad/webpack.config.devtools.js
* don't make source map files
* use a module cache to so that modules don't change IDs. the effect is the diff goes from `70K` => `5K` lines
> (WIP) improve config

- packages/devtools-source-map/README.md
- packages/devtools-source-map/src/index.js
When this is landed in m-c, I think we'll want full control over the URL used, so that the worker and package can easily be placed wherever makes the most sense in the tree.
> Fully configurable source map worker URL

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/webpack.config.js
- packages/devtools-launchpad/yarn.lock
Add `autoprefixer` plugin and use it while bundling with webpack.
Associated Issue devtools-html/debugger.html#1838
For #128 We'll need a `browserslist` config (in `package.json` or a separate file?). This should probably be in `debugger.html`.
> Use autoprefixer postcss plugin

- packages/devtools-sham-modules/client/shared/components/tree.js
Associated Issue: devtools-html/debugger.html#2256
* Removes focusing the next node in the tree (either the child of the branch or the next leaf) when pressing the right arrow
> [Sources] Only expand tree when right arrow pressed

- packages/devtools-source-map/src/util.js
Comes from devtools-html/debugger.html#2307.
Since the source-map-worker is moving to devtools-core, this need needs to be merged so that clojure support can be maintained.
> add clojure content type to worker

- packages/devtools-launchpad/src/lib/themes/variables.css
This is related to https://github.com/devtools-html/debugger.html/issues/2304
I added a css variable for a darker hover state on toolbar and pane elements in the dark theme.
> Add toolbar background hover state variable

- packages/devtools-source-map/package.json
- packages/devtools-source-map/yarn.lock
The debugger is currently including different versions of the shared dependencies.
[yarn.lock](https://gist.github.com/aef4f8b764d50d2fededeeea88a54f20)
> bump source-map deps

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/yarn.lock
In the process of moving the search state to Redux I've noticed a warning in the console due to the version of react-immutable-proptypes we had as a dependency.
```
23:11:37.011 Warning: You are manually calling a React.PropTypes validation function for the `searchModifiers.caseSensitive` prop on `Editor`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details. 1 debugger.js:2580:10
```
This updates the package which has fixes for this warning.
> Bump react-immutable-proptypes version

- packages/devtools-launchpad/src/utils/L10N.js
Calling setBundle() multiple times can merge new L10N strings. It's useful to support multiple L10N files.
> Support setting multiple L10n bundle

- packages/devtools-launchpad/webpack.config.js
This dramatically simplifies our JS transform strategy to be: exclude all node modules except for our own.
> Simplify transform pattern

- packages/devtools-sham-modules/shared/client/main.js
- packages/devtools-sham-modules/shared/webconsole/client.js
FF devtools loader allows you to require cyclic dependency but it is broken in node.
A workaround fix for solving cyclic dependency in WebConsoleClient and LongStringClient, which causes { LongStringClient } = require() always return empty object within node module system.
> Fix cyclic dependency in WebConsoleClient and LongStringClient

- packages/devtools-launchpad/src/reducers/tabs.js
Currently your filter is cleared when their is a tab refresh because
the `getTabs` function runs a `clearTabs` to reset the tabs before
adding new tabs.  This makes the `CLEAR_TABS` action more clear by not
creating the side effect of destroying other state by returning the
`initialState`.
> persist the filter state when clearing tabs

- packages/devtools-sham-modules/client/shared/components/search-box.js
- packages/devtools-sham-modules/client/shared/components/tabs/tabbar.css
- packages/devtools-sham-modules/client/shared/components/tabs/tabbar.js
- packages/devtools-sham-modules/client/shared/components/tabs/tabs.css
- packages/devtools-sham-modules/client/shared/components/tabs/tabs.js
- packages/devtools-sham-modules/index.js
add search-box and tabs component into `devtools-sham-modules` since they have dependencies in `sham-modules`.
put requires in alphabet order.
(I'm not sure if its fine to add shortcut in index.js, with that way the unused `search-box` component will be bundled into `debugger.html`)
> add search-box component into sham-modules

- .flowconfig
- packages/devtools-source-map/README.md
- packages/devtools-source-map/bin/getConfig.js
- packages/devtools-source-map/configs/firefox-panel.json
- packages/devtools-source-map/src/index.js
This adds a Firefox panel config for `devtools-source-map`, which is used when this is landed as a bundle in m-c.
Since we're landing a standalone bundle in m-c, we can't rely on config values from apps like the debugger anymore, so we need to set config data (currently just the worker URL) in this package.
> Set source map worker URL in Firefox

- packages/devtools-modules/client/shared/components/splitter/SplitBox.js
- packages/devtools-modules/index.js
This updates the splitbox so that the component requires the CSS directly.
This will let us remove the splitbox CSS code from the debugger, which was previously being duplicated
> Splitter - require css directly

- README.md
Use a table instead of a list
Move all the links below
Link to the package directory readme section instead of the readme file.  For example instead of linking to [devtools-config](../tree/master/packages/devtools-config/README.md) we link to [devtools-config](../tree/master/packages/devtools-config/#readme) which takes you to the directory where the readme is but not the actual file.
> update the formatting for the npm package links

- packages/devtools-launchpad/src/components/Tabs.css
Mouse cursor when hovering over tabs in Launchpad is `default` when
there are more than one tabs.
|  |  |
|---------|------|
|Before|![before](https://cloud.githubusercontent.com/assets/1755089/24511110/b3391860-1588-11e7-8351-15356db14020.gif)|
|After|![after](https://cloud.githubusercontent.com/assets/1755089/24511126/bc4e4376-1588-11e7-8382-058aabbb9135.gif)|
> [launchpad] fix cursor for tab

- packages/devtools-modules/client/shared/prefs.js
Fix error which caused by #301. Services module should be exported directly.
> Fix Services not found error

- packages/devtools-launchpad/bin/firefox-driver.js
Fix bug where "yarn firefox" would not open port 6080 for remote debug on Windows platform
> Fix to send correct args to Windows FF

- packages/devtools-modules/client/shared/prefs.js
Port back a fix made on mozilla-central (https://bugzilla.mozilla.org/show_bug.cgi?id=1356569)
> Bug 1356569 - Remove optional trailing parameters (from mozilla-central)

- packages/devtools-source-map/src/tests/getContentType.js
- packages/devtools-source-map/src/util.js
This changes getContentType to only check the suffix a single time, and
to look for the ".".  It also removes isJavaScript - that function was
not exported, and so the "contentType" code there was unused.
> Simplify content type computation

- packages/devtools-source-map/src/source-map.js
Export hasMappedSource.  This imported by worker.js, so it ought to be
available.
Fixes #311
> export hasMappedSource

- packages/devtools-source-map/src/source-map.js
Change getOriginalLocation to put the original URL in the result
object.  This is simpler for clients that don't want to maintain their
own mapping of original IDs to URLs.
> Put original URL in getOriginalLocation result

- packages/devtools-license-check/bin/devtools-license-check
- packages/devtools-license-check/package.json
Julien pointed out that the inclusion of the GPL in the whitelist was an
error; which it was, I didn't notice this when I switched from my unix
scriptish approach to checking to using Jordan's code.
This removes the GPL, LGPL, and Artistic license; none of which we seem
to need.
> Do not allow the GPL

- packages/devtools-source-map/src/path.js
- packages/devtools-source-map/src/tests/isURL.js
Currently, isURL does not recognize data: URLs.  This is the cause of
https://bugzilla.mozilla.org/show_bug.cgi?id=1360357
This patch fixes it in the obvious way.
> Recognize data: in isURL

- packages/devtools-launchpad/src/components/LandingPage.css
- packages/devtools-launchpad/src/components/LandingPage.js
- packages/devtools-launchpad/src/constants.js
- packages/devtools-launchpad/src/selectors.js
- packages/devtools-launchpad/stories/index.js
- Removes "Launch `Target`" when targets detected
- Shows "Launch `Target`" when no targets detected
- Shows "Please open a new tab in `target`" in connected state
- ⚠️ Shows nothing when "Node" tab is detected, I need help / advise on what to show when node tab selected
The PR was submitted as part of #goodnessSquad open source contribution event
Thanks to @amitzur for mentoring
> Resolves #161 [Launchpad] Show Launch button when no targets exist

- circle.yml
- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/tools/tests/webpack.config.js
- packages/devtools-launchpad/webpack.config.js
- packages/devtools-launchpad/yarn.lock
- packages/devtools-source-editor/bin/dev-server.js
- packages/devtools-source-editor/examples/index.js
- packages/devtools-source-editor/index.js
- packages/devtools-source-editor/src/utils.js
- packages/devtools-utils/src/worker-utils.js
1. adds some tests for the config
2. generalizes the exclude patter to always include `devtools-` packages
3. switches source-editor to commonjs requires (will now work w/ yarn link)
4. cleans up source-editor and adds a bit more docs
> Fix source editor linking

- packages/devtools-launchpad/src/reducers/tabs.js
Small PR that fixes state corruption when a redux action `CLEAR_TABS` triggered.
`setIn` function expects an array as path specifier, it was a string before
> Prevent state corruption when clearing tabs

- packages/devtools-source-map/src/path.js
- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/tests/fixtures/absolute.js
- packages/devtools-source-map/src/tests/fixtures/absolute.js.map
- packages/devtools-source-map/src/tests/source-map.js
_setSourceMapRoot was not properly resolving a location relative to an
absolute source root.  This manifested in GWT Super Dev Mode (I really
can't type that enough) as a request for an invalid original source,
like:
http://127.0.0.1:9876/sourcemaps/webadmin/http:/127.0.0.1:9876/sourcemaps/webadmin/com/google/gwt/core/client/GWT.java
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1355126
> Correctly resolve original locations relative to absolute source roots

- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/tests/fixtures/noroot.js
- packages/devtools-source-map/src/tests/fixtures/noroot.js.map
- packages/devtools-source-map/src/tests/source-map.js
The previous patch was again wrong, this time not properly handling the
case where sourceRoot is not defined.  This patch fixes it in the
obvious way.
> Handle non-existing sourceRoot correctly

- packages/devtools-source-map/LICENSE
- packages/devtools-source-map/bin/copy-assets.js
- packages/devtools-source-map/bin/getConfig.js
- packages/devtools-source-map/src/assert.js
- packages/devtools-source-map/src/index.js
- packages/devtools-source-map/src/path.js
- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/tests/getContentType.js
- packages/devtools-source-map/src/tests/isURL.js
- packages/devtools-source-map/src/tests/source-map.js
- packages/devtools-source-map/src/util.js
- packages/devtools-source-map/src/worker.js
The devtools-source-map package already has the right MPL-2.0 license in package.json, so we're already good.
But it doesn't have a LICENSE file or license headers in source files. MPL-2.0 requires this, and this is what this PR does.
> Devtools source map license

- packages/devtools-source-editor/LICENSE
- packages/devtools-source-editor/bin/dev-server.js
- packages/devtools-source-editor/examples/index.css
- packages/devtools-source-editor/examples/index.html
- packages/devtools-source-editor/examples/index.js
- packages/devtools-source-editor/index.js
- packages/devtools-source-editor/src/source-editor.css
- packages/devtools-source-editor/src/source-editor.js
- packages/devtools-source-editor/src/utils.js
The code in this package originated on mozilla-central, under the MPL2.0 license, and also mentioned MPL2.0 in the package.json file. It only lacked the LICENSE file at the root as well as license headers at the top of each source file.
This is what this PR does.
> Adding the missing LICENSE file and headers in source-editor

- packages/devtools-launchpad/bin/validate-deps.js
- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/tools/tests/webpack.config.js
- packages/devtools-launchpad/yarn.lock
This makes the `validate-deps.js` script work for me on Windows.
It used to fail trying to get the yarn lock file parser before. Turns out the `parse-yarn-lock` module we were using didn't work for me on Windows. I think @clarkbw had already [reported it here](https://github.com/cdaringe/parse-yarn-lock/pull/1) but I'm not seeing a resolution to this. I think this was itself waiting on another [yarn fix](https://github.com/yarnpkg/yarn/pull/3397) that hasn't landed.
I've been trying my luck at different options, and ended up trying to require the yarn lockfile parser directly, which seems to work. No need to have a dependency on yarn in `package.json` it seems, we can just use the parser.
One thing though, my SublimeText editor was viewing the file with Windows line endings, which was …
> Make validate-deps use the default yarn parser

- packages/devtools-reps/src/reps/function.js
- packages/devtools-reps/src/test/mochitest/test_reps_function.html
Fixes #413 
Added a props `parameterNames` for now since we don't have the data directly in the grip.
This way, the debugger will be able to use the Reps (since there we can retrieve parameter names from the AST)
@jbhoosreddy if you have some time I'd like you to review this PR since I think you're the one that created `previewFunction` , thanks !
---
Mochitest are passing locally
> Allow to pass parameter names to Function Rep

- package.json
- packages/devtools-launchpad/src/client/firefox-types.js
- packages/devtools-launchpad/src/client/firefox.js
- packages/devtools-launchpad/src/utils/L10N.js
- yarn.lock
This is to fix all the flow errors in debugger after bumping a flow-bin version. I just changed the version to 0.47 and patched all the errors by inserting `any` and some variable name to where seemed appropriate to make flow run without errors after update.
> Bump version of flow-bin

- packages/devtools-reps/src/reps/tests/failure.js
The failure test throws an exception on purpose, so we can
catch it and render an ad-hoc component.
However, jest would still output the exception when running the
test, which can be a bit confusing since the test is still passing.
Overriding `console.error` for the time of the test allow us to
get rid of the exception message.
> Override console.error in Failure test.

- packages/devtools-source-editor/src/utils.js
1. Add a general purpose helper: `getTokenLocation` we'll be able to remove it from the debugger
2. add a speedup: `codeMirror.operation`
> Editor improvements

- lerna.json
- package.json
- yarn.lock
Just updated lerna version to `v2.0.0-rc.5`. It just throw errors less often while doing `yarn install` for me.
> Update lerna to latest v2.0.0-rc.5

- packages/devtools-reps/package.json
- packages/devtools-reps/src/object-inspector/tests/__snapshots__/object-inspector.js.snap
- packages/devtools-reps/src/object-inspector/tests/object-inspector.js
- packages/devtools-reps/src/reps/function.js
- packages/devtools-reps/src/reps/tests/error.js
- packages/devtools-reps/yarn.lock
Fixes #472.
There were only tests for utils functions.
This adds some basic test for the ObjectInspector itself.
> Add object inspector tests.

- packages/devtools-reps/src/reps/attribute.js
- packages/devtools-reps/src/reps/comment-node.js
- packages/devtools-reps/src/reps/date-time.js
- packages/devtools-reps/src/reps/document.js
- packages/devtools-reps/src/reps/element-node.js
- packages/devtools-reps/src/reps/error.js
- packages/devtools-reps/src/reps/event.js
- packages/devtools-reps/src/reps/function.js
- packages/devtools-reps/src/reps/grip-array.js
- packages/devtools-reps/src/reps/grip-map.js
- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/long-string.js
- packages/devtools-reps/src/reps/null.js
- packages/devtools-reps/src/reps/object-with-text.js
- packages/devtools-reps/src/reps/object-with-url.js
- packages/devtools-reps/src/reps/promise.js
- packages/devtools-reps/src/reps/regexp.js
- packages/devtools-reps/src/reps/rep.js
- packages/devtools-reps/src/reps/stylesheet.js
- packages/devtools-reps/src/reps/tests/object.js
- packages/devtools-reps/src/reps/text-node.js
- packages/devtools-reps/src/reps/undefined.js
- packages/devtools-reps/src/reps/window.js
Fixes #480
Modify the `getRep` and `supportsObject` functions so we can pass this `noGrip`
property to it.
Add tests in the `Obj` rep which try to render stubs representing different
remote object, with the `noGrip` prop, and makes sure it uses the `Obj` rep,
and not the "remote" one.
> Add a prop to force object to be rendered using non-remote reps

- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/stubs/grip.js
There was a bug in the Grip rep in long mode if the object had more than 10 properties.
This wasn't caught by tests because we handemade the stub, which ended up not looking
the same from what we actually get from the server.
> Show a "more…" label when needed.

- packages/devtools-components/src/tree.js
- packages/devtools-reps/bin/copy-assets.js
- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/reps/date-time.js
- packages/devtools-reps/src/reps/document.js
- packages/devtools-reps/src/reps/function.js
- packages/devtools-reps/src/reps/grip-array.js
- packages/devtools-reps/src/reps/grip-map.js
- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/object-with-url.js
- packages/devtools-reps/src/reps/promise.js
- packages/devtools-reps/src/reps/rep.js
- packages/devtools-reps/src/reps/reps.css
- packages/devtools-reps/src/reps/stylesheet.js
- packages/devtools-reps/src/reps/window.js
This patch removes CSS references to `objectLink` and adds an `objectTitle` class on all the Reps that have a title.
This also allow the tree items to be wrapped, unless a `noWrap` prop is passed to the object inspector.
> Tweak styling in order to integrate it in the console

- packages/devtools-license-check/bin/devtools-license-check
This adds another whitelisted license
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
Another option is to whitelist https://github.com/aadsm/jschardet
It would be nice to move some of the launchpad deps to dev deps in theory, but then we would need to add many of those deps to the debugger because they're not auto-installed.
here's the initial offender: https://github.com/devtools-html/debugger.html/pull/3287
> Add LGPL-2.1+ license

- packages/devtools-reps/src/reps/array.js
- packages/devtools-reps/src/reps/grip-array.js
- packages/devtools-reps/src/reps/grip-map.js
- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/object.js
- packages/devtools-reps/src/reps/reps.css
- packages/devtools-reps/src/reps/stubs/grip-array.js
- packages/devtools-reps/src/reps/stubs/grip-map.js
- packages/devtools-reps/src/reps/tests/array.js
- packages/devtools-reps/src/reps/tests/event.js
- packages/devtools-reps/src/reps/tests/grip-array.js
- packages/devtools-reps/src/reps/tests/grip-map.js
- packages/devtools-reps/src/reps/tests/grip.js
- packages/devtools-reps/src/reps/tests/object.js
- packages/devtools-reps/src/reps/tests/promise.js
Basically, for the most case we switched from `more…` to `…` only.
We also re-use the ellipsis in TINY mode for arrays and objects.
Now empty arrays and objects in TINY mode should render respectively
as `[]` and `{}`, and non-empty arrays and objects `[…]` and `{…}`.
This should indicate more clearly and in a more consistent way that
there are hidden properties/items in what we render, and encourage the
user to expand the object/array to check what it really contains.
Doing this work was also a great opportunity to be more consistent through
all the reps, and mostly have the same output for RDP and "plain" objects
for the same test cases.
> Modify how we indicate there is more to see in an object.

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/object-inspector.js
- packages/devtools-reps/src/object-inspector/utils.js
- packages/devtools-reps/src/reps/accessor.js
- packages/devtools-reps/src/reps/rep.js
- packages/devtools-reps/src/reps/stubs/accessor.js
- packages/devtools-reps/src/reps/stubs/grip.js
- packages/devtools-reps/src/reps/tests/accessor.js
- packages/devtools-reps/src/reps/tests/grip.js
This PR adds an `Accessor` rep which handle object with getter and/or setter.
I choose a dedicated Rep because the plan is to make it evolve in the future,
for example to be able to evaluate a property with a getter.
This also adds pseudo `<get>` and `<set>` properties on the ObjectInspector so they can also be inspected, like we could in the VariableView.
> Display getters and setters in Reps and in the ObjectInspector.

- packages/devtools-source-editor/src/source-editor.js
Fixes https://github.com/devtools-html/debugger.html/issues/3357
Accounts for the offset of the editor bc tabs take space too.
> Account for editor tabs

- packages/devtools-reps/src/object-inspector/stubs/performance.js
- packages/devtools-reps/src/object-inspector/tests/object-inspector.js
- packages/devtools-reps/src/object-inspector/utils.js
In getObjectProperties, we may receive a safeGetterValues property in addition to
the ownProperty one. This PR handle the data from this property so we can show
these values as children in the ObjectInspector.
> Handle safeGetterValue in the ObjectInspector.

- packages/devtools-utils/src/privileged-network-request.js
- packages/devtools-utils/src/tests/worker-utils.js
- packages/devtools-utils/src/worker-utils.js
This changes the network request code and the worker handler code to
catch exceptions and report them to the caller via their promise
results.  It also changes the network request code to provide an error
message when the XHR's statusText is empty; this can happen when an
invalid URL is used.
> Handle exceptions in network request and worker utilities

- packages/devtools-source-map/src/source-map.js
Source mapping errors are going to be shown in the web console in
https://bugzilla.mozilla.org/show_bug.cgi?id=1345533.  There's no need
to report them here, and anyway these reports only show up in the
browser console.
> Don't call console.error from source-map.js

- packages/devtools-reps/src/launchpad/index.js
We use to add the content of safeGetterValues into the ownProperties property we get
from client.getPrototypeAndProperties.
This could lead to differences between the launchpad and the toolbox,
so we remove that piece of code to avoid any confusion.
> Do not override getPrototypeAndProperties response.

- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/prop-rep.js
- packages/devtools-reps/src/reps/stubs/grip.js
- packages/devtools-reps/src/reps/symbol.js
- packages/devtools-reps/src/reps/tests/grip.js
This patch adds the support for the `ownSymbols` property
introduced in [Bug 881480](https://bugzilla.mozilla.org/show_bug.cgi?id=881480),
as well as some tests (and stubs) to ensure they are rendered as expected.
> Display symbols properties on objects.

- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/tests/grip-array.js
- packages/devtools-reps/src/reps/tests/grip.js
In some cases, we can have a grip without a preview property (e.g. for the following object `[{}]`). Because the grip was only supporting object with preview property, the grip was rendered with the default rep (i.e. Object), and thus could be incorrect.
This patch fixes this and adds some tests to make sure we handle this case as expected.
> Fix bugs for grips without preview property.

- packages/devtools-reps/src/reps/grip-map-entry.js
- packages/devtools-reps/src/reps/grip-map.js
- packages/devtools-reps/src/reps/rep.js
- packages/devtools-reps/src/reps/stubs/grip-map-entry.js
- packages/devtools-reps/src/reps/tests/grip-map-entry.js
- packages/devtools-reps/src/reps/tests/grip-map.js
When we fetch entries from the server, we get a grip with a "mapEntry" type that we weren't handling previously.
This patch adds a Rep to deal with those kind of grips and harmonize the way we render map entries (even in the map preview), to match what we had previously in the VariableView (e.g. `Map {a → 1}` instead of `Map {a: 1}`, this works better in an OI context where you can have `0: a → 1`, instead of an awkward `0: a: 1`).
~This relies on https://github.com/devtools-html/devtools-core/pull/531 (Some tests are failing without this patch).~  https://github.com/devtools-html/devtools-core/pull/531 Is now merged, CI should be happier.
> Add a MapEntry Rep.

- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/object-inspector.js
- packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-properties.js
- packages/devtools-reps/src/object-inspector/utils.js
First, we add the missing rule for the default-property class.
This patch changes how we style default properties node in
objects. Previously, we were looking for properties with the
same name as a window ownProperty. This could be dangerous
since you can have properties with the same name as one in
Window, but not necessarely under the window object.
Also, this can be weird to dim all the window default properties
when you expanded the node. If you did so, you are probably
interested in seeing what's inside.
Taking this into account, this patch applies the default-property class
to the default properties node and __proto__ ones, but only when they are
collapsed.
> Change default properties node styling

- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/tests/fixtures/missingmap.js
- packages/devtools-source-map/src/tests/source-map.js
My previous patch in this area was mistaken - it correctly allowed
errors from _fetchSourceMap to be propagated to the caller, but it
also cached the rejected promise in sourceMapRequests, resulting in
the same error being reported via other APIs.  This patch fixes the
oversight by caching a non-rejecting promise; this results in the
other APIs keeping their previous behavior.
> Do not put a rejected promise into sourceMapRequests cache

- packages/devtools-utils/src/tests/worker-utils.js
- packages/devtools-utils/src/worker-utils.js
This initial PR adds the streaming worker.
I'm still working on some kinks here. But this is relatively how it should look.
Issue: On the browser, it works better but in the jest test environment using something like
````js
function delay(milliseconds) {
return function(result) {
return new Promise(function(resolve, reject) {
setTimeout(function() {
resolve(result);
}, milliseconds);
});
};
}
````
would never resolve for `await` ing callers. Which prevents the tests from passing. Returning promises which resolve without setTimeout still work in the tests.
@codehag @jasonLaster @bomsy 
I want to tidy this up a bit. But suggestions welcome here. 😉
> adds streaming worker

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/object-inspector.js
- packages/devtools-reps/src/object-inspector/tests/utils/node-is-window.js
- packages/devtools-reps/src/object-inspector/utils.js
This is done to fill the need of the debugger Scopes panel,
since the global Window object is always shown.
> Add a prop to dim top level window node.

- packages/devtools-contextmenu/menu.js
See bug 1384965 for more details:
https://bugzilla.mozilla.org/show_bug.cgi?id=1384965
Honza
> Avoid space between contexty menu and its submenu (bug 1384965)

- packages/devtools-contextmenu/menu.css
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1384892
Honza
> Make a little space between a label and submenu arrow (bug 1384892)

- packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-numerical-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/node-supports-bucketing.js
- packages/devtools-reps/src/object-inspector/utils.js
Fixes #496 
Fixes #538 
Fixes #560
We use the GripArray supportsObject function to get nodes which can represents array-like objects so we cover more than plain arrays (DocumentFragment, NodeList, Typed-Arrays, …).
There was also a flaw in how we computed the last bucket label.
Also, now we don't create a bucket if there will be only one item in it.
And finally we show at most a hundred buckets per level.
When inspecting very-large arrays (> 10000 items), the UI would freeze because we were creating too much buckets at once.
This patch solves this by having at most a hundred bucket per-level, and then using sub-buckets, like we did in the VariableView.
Tests were added to ensure everything is working like it should, and since the test file was getting bigger, I created a dedicated test …
> Improve bucketing

- packages/devtools-reps/src/index.js
This is needed for the debugger which uses the `getChildren` function in its Preview component.
> Expose ObjectInspector utils

- packages/devtools-utils/src/privileged-network-request.js
This change privileged-network-request to use fetch rather than
XMLHttpRequest; and also changes it to respect the "loadFromCache"
option.  Fixes #551.
> Use fetch in privileged-network-request and inhibit caching

- packages/devtools-reps/src/reps/string.js
- packages/devtools-reps/src/reps/tests/string-with-url.js
This is needed in the console for example so we don't navigate to the URL **in** the toolbox as well
> Add preventDefault on url onClick callback.

- packages/devtools-modules/index.js
- packages/devtools-modules/src/key-shortcuts.js
This is also related to bug 1388368
KeyShortcuts object should be exported the same way as in m-c, so it's easily exchangeable.
Honza
> Unify the way how KeyShortcuts is exported with m-c

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/basic.js
We were always rendering a simple rep when the value of the root node was a primitive.
**But,** this was messing with the watch expressions panel in the debugger, since we **do** want to see the name there (e.g. `3 + 1: 4`).
> Do not force Rep render on root when it has a name.

- packages/devtools-modules/src/Services.js
- packages/devtools-modules/src/prefs.js
- packages/devtools-modules/src/tests/prefs-helper.js
- packages/devtools-modules/src/tests/services-prefs.js
I tested locally this change by modifying the corresponding code in the debugger bundle, and my breakpoints, tabs, expressions were still the ones from the previous session (which means that changing the type from Char to String didn't seem to create any issue).
Note that this won't fix existing bad preferences, such as the one that triggered https://bugzilla.mozilla.org/show_bug.cgi?id=1388825 , since the issue occurs on save.
> Issue #580 : switch to type String for Json prefs

- packages/devtools-reps/package.json
- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/classnames.js
- packages/devtools-reps/yarn.lock
This adds an `inline` class to the tree which display the tree as `inline-block`, which might be useful for some consumer (e.g. the console where you can have multiple ObjectInspectors side by side; even if for now we are using flexbox to lay out them).
This changes needed devtools-components 0.0.2 for the Tree component to handle the classname override.
Also, this was a good opportunity to add tests for the class names in the object inspector.
> Add a prop to have ObjectInspector inline

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/development-server.js
updates the minimum node version to 7.x. We need this because we use Object.keys i think.
This also prettifies development.server :P
> Bump node version

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/function.js
- packages/devtools-reps/src/reps/function.js
- packages/devtools-reps/src/reps/tests/function.js
- packages/devtools-reps/src/reps/tests/grip.js
We introduced a simplified prop to functions in order to not display the function keyword on some object.
This seems to be redundant with the concept of mode. So here we drop the prop, and do the same check with the TINY mode.
> Replace the simplified prop check with TINY mode.

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/function.js
There were a bug when the mode was not defined.
We default to TINY mode in such case, but we didn't
handled that case for function render.
> Fix function render.

- packages/devtools-reps/src/launchpad/samples.js
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/proxy.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/proxy.js
- packages/devtools-reps/src/object-inspector/tests/utils/get-children.js
- packages/devtools-reps/src/object-inspector/utils.js
Previously, when the user expanded a Proxy object, we loaded the properties
of the target, which is only half the information the user might want to see.
Now we build 2 ndoes, target and handler, that can be expanded as well so
the user can inspect the Proxy object properly.
Some tests were added to make sure we handle proxies as expected, and the
setExpanded function was refactored a bit to be more readable.
> Handle Proxy target and handler in ObjectInspector.

- packages/devtools-connection/src/debugger/client.js
**Add ObjectClient.enumSymbols function**
This feature was introduced in [Bug 1392614](https://bugzilla.mozilla.org/show_bug.cgi\?id\=1392614).
Here, we only add the ObjectClient part so we can use it in the launchpad.
**Sync fix from [Bug 1392954](https://bugzilla.mozilla.org/show_bug.cgi%5C?id%5C=1392954)**
Basically this allow us to use plain promises when working with ObjectClient functions
> Sync changes from m-c in devtools-connection

- packages/devtools-launchpad/webpack.config.devtools.js
- packages/devtools-launchpad/webpack.config.js
- packages/devtools-source-editor/examples/index.js
* add an extra `options` option for passing exclude mappings so the debugger can decide what to exclude
* drop postcss from production builds. we don't want to add prefixes or drop `inline-start` props
> Update lanuchpad config

- packages/devtools-launchpad/webpack.config.js
Since the webpack 3 update, if you add a babelExcludes to the webpack config
you get an error message stating that you tried to pass in an unknown property.
This patch uses the new options argument as a way to pass babelExcludes.
> Get babelExcludes from options

- packages/devtools-modules/src/source-utils.js
- packages/devtools-modules/src/tests/source-utils.js
- packages/devtools-utils/src/network-request.js
- packages/devtools-utils/src/tests/.eslintrc
- packages/devtools-utils/src/tests/network-request.js
This takes the code from https://hg.mozilla.org/mozilla-central/file/018b3829d0a7/devtools/client/shared/source-utils.js and https://hg.mozilla.org/mozilla-central/file/018b3829d0a7/devtools/client/shared/test/unit/test_source-utils.js for the test. The test was converted to jest.
This is needed so we can import Stacktrace and Frames component from mozilla-central as well
> Add source-utils from m-c into devtools-modules

- packages/devtools-reps/package.json
- packages/devtools-reps/yarn.lock
Bump up the launchpad
Add direct "svg-inline-loader" dependency since we use it and we were retrieving it from another dependency, which isn't ideal.
Tweak the jest config for the upcoming ObjectInspector patch
> Update devtools-reps package.json

- packages/devtools-reps/src/reps/array.js
- packages/devtools-reps/src/reps/grip-array.js
- packages/devtools-reps/src/reps/grip-map.js
This will help us for the ObjectInspector to know if a Rep needs to have buckets
> Add and export getLength function on Array and Map reps.

- packages/devtools-utils/package.json
- packages/devtools-utils/src/tests/worker-utils.js
- packages/devtools-utils/src/worker-utils.js
Error can't be sent using postMessage.
See https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
This patch converts errors to strings before reporting them.
> Convert Error to string when worker method fails

- packages/devtools-launchpad/src/index.js
Associated Issue: https://github.com/devtools-html/debugger.html/issues/2840
* Our themes weren't loading soon enough so we would get occasional miscolored flashes. This is because we were trying to use theme variables before they existed and the browser fell back to using black. Moving this block up before the render makes sure we have our config and theme ready before rendering.
> Move the theme loading to before we render our react app.

- packages/devtools-utils/src/tests/worker-utils.js
- packages/devtools-utils/src/worker-utils.js
Fixes an annoying issue where the worker would crash with a typeError where `removeEventListener` was not defined on undefined.
> Handle tasks completing when the worker is shutdown

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/postcss.config.js
- packages/devtools-launchpad/yarn.lock
- packages/devtools-modules/src/themes/dark-theme.css
- packages/devtools-modules/src/themes/firebug-theme.css
- packages/devtools-modules/src/themes/light-theme.css
Associated Issue: #641 
We would like to remove the theme namespacing because it is making it harder to sync. Eventually it would be nice to pull these styles from searchfox, but we don't need to do that now. 
Next steps:
1. get this working
2. see what regressions exist between themes and rectify that. I'm happy to add a script that does the diff so it's easy to see what's different and fix it.
> Remove theme namespaces

- packages/devtools-components/src/tree.css
- packages/devtools-components/src/tree.js
- packages/devtools-components/stories/tree.js
This PR is mainly about adding a fake border to the tree, as well as proper focused and hover styling, which match [the devtools photon guideline](https://docs.google.com/document/d/1AJ7oHC7akXJiliheHjhFc4fTonaN31Eo_P2M8gssL8s/edit#heading=h.o8ous6wzxnb5): 
The border is added with a linear-gradient background-image so we can avoid to have dedicated html elements to only have borders and width.
Everything relies on CSS custom properties so consumers can change whatever they want by overiding the properties in their CSS (i'm thinking about the source tree in the debugger that might not need border ? ).
CI is still failing because lerna make devtools-reps use the devtools-components from the tree instead of the one from npm, but everything is green locally.
> Add styling to the tree

- packages/devtools-components/src/tests/__snapshots__/tree.js.snap
- packages/devtools-components/src/tests/tree.js
- packages/devtools-components/src/tree.js
Previously, the Tree component relied on the length of the result of `getChildren` to know if a node was expandable and render an arrow in front of it.
But it might happen in some consumer that a node **is** expandable but `getChildren` returns an empty array at the moment.
This is the case for the ObjectInspector where properties are lazily loaded, so at the time we render the tree, some nodes might not have children _yet_ .
Adding this `isExpandable` prop gives the consumer the ability to tell if a given node is expandable or not, since it's the one that knows the logic better.
This PR adds a test as well as test to make sure the prop works as intended.
> Add a isExpandable prop callback to the Tree component

- .gitignore
When running yarn install on the root of devtools-core, `lerna bootstrap` is creating an assets folder which contains a module-manifest.json file.
This should either be ignored or added to source control.
> chore: add assets/ to .gitignore

- packages/devtools-reps/package.json
- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap
- packages/devtools-reps/src/object-inspector/tests/test-utils.js
- packages/devtools-reps/src/shared/images/Svg.js
- packages/devtools-reps/src/shared/images/arrow.svg
- packages/devtools-reps/yarn.lock
This allow us to remove our custom arrow and custom styles.
We add an extra `object-inspector` classname on the tree so we can override CSS properties safely
> Use arrow and styles from the Tree component

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/entries.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/proxy.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/state.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/function.js
Doing this makes the tree less cluttered.
Before: 
After:
> Render Reps as TINY mode when the node is expanded.

- packages/devtools-source-map/package.json
- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/tests/fixtures/if.js
- packages/devtools-source-map/src/tests/fixtures/if.out.js
- packages/devtools-source-map/src/tests/fixtures/if.out.js.map
- packages/devtools-source-map/src/tests/helpers.js
- packages/devtools-source-map/src/tests/locations.js
- packages/devtools-source-map/src/tests/source-map.js
- packages/devtools-source-map/src/utils/fetchSourceMap.js
fixes: https://github.com/devtools-html/debugger.html/issues/3399
We currently have a problem where the user adds a breakpoint on line 5 of the example below at the top of the IF statement and the breakpoint slides to line 8 at the bottom of the IF statement definition.
This happens because when convert the location from original, to generated, and back to original, the location moves from line 5 to line 8. We should support symmetry in mapping where the location does not change if when we map it` toOriginal(toGeneral(oLoc))`. The analogy is 2 inches is 5.08cm and 5.08cm is 2inches. Changing units should not change the values.
```js
function componentWillReceiveProps(nextProps) {
console.log('start');
const { selectedSource } = nextProps;
if (
nextProps.startPanelSize !== …
```
> Support symmetric locations

- packages/devtools-reps/src/reps/element-node.js
- packages/devtools-reps/src/reps/stubs/element-node.js
- packages/devtools-reps/src/reps/tests/__snapshots__/element-node.js.snap
- packages/devtools-reps/src/reps/tests/element-node.js
Associated Issue: #670
Fixes tiny mode representation of classname for element-node rep.
* Use trim() instead of regexp to trim the classname attribute value 
* use split with a regexp `/\s+/` rather than with a plain space string `" "`
Added new unit test to cover the issue. I think I stumbled upon a problem with enzyme while writing the test.
> Issue #670 - fix TINY mode for element-node with spaces in classname

- packages/devtools-source-map/package.json
this bumps the source map worker. 
Would it be alright if i updated mc when I update the debugger? the two should be in sync
> bump source map worker

- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/reps/attribute.js
- packages/devtools-reps/src/reps/document.js
- packages/devtools-reps/src/reps/element-node.js
- packages/devtools-reps/src/reps/reps.css
- packages/devtools-reps/src/reps/string.js
- packages/devtools-reps/src/reps/tests/window.js
- packages/devtools-reps/src/reps/window.js
This patch changes a few CSS variables to match the Devtools Photon design spec.
We take this as an opportunity to have more consistent look and classnames across
the different reps (e.g. window, document and location).
Updated screenshot:
> Photonize Reps and ObjectInspector.

- packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-properties.js
- packages/devtools-reps/src/object-inspector/utils/node.js
The filter was failing if a property was undefined or null.
I need to check how we can get those kind of values, but at the moment, this hotfix will eliminate them
> Fix make node for properties

- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/basic.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/entries.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/getter-setter.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/proxy.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/state.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/function.js
Fixes #675
This is more consistent with the way we already render objects in Reps.
> Remove extra space after object delimiter in ObjectInspector nodes.

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/state.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/release-actors.js
- packages/devtools-reps/src/object-inspector/tests/component/state.js
The actors property on the ObjectInspector state keep track of all the actors that need to be
released when we're done with the component. The problem of releasing the root actor is that
if the comsumer of the OI was simply hidden, and then shown again, the user would not be
able to expand the objectInspector.
Here we don't track root actors so the consumer handle the lifetime of the root actors it handles.
This causes no issues for non-root actors, since the ObjectInspector is unmounted, if the user
want to expand it again after a hide/show cycle again, we'll end up creating new ObjectClient (and
thus actors).
> Don't add root actors to the state of the ObjectInspector.

- packages/devtools-reps/src/object-inspector/tests/component/create-object-client.js
- packages/devtools-reps/src/object-inspector/tests/component/entries.js
- packages/devtools-reps/src/object-inspector/tests/component/properties.js
- packages/devtools-reps/src/object-inspector/tests/component/proxy.js
- packages/devtools-reps/src/object-inspector/utils/client.js
Since we don't know what the ObjectClient we get looks like, it might happens that it doesn't have
the method we try to call (e.g. connecting to an older server, you will miss the enumSymbols function).
Wrapping everything in try/catch blocks mitigate the risk of crashing the ObjectInspector (in the beforementioned case, everything will be fine except we wouldn't get symbol properties, which seems acceptable).
> Wrap provided objectClient function calls in try/catch blocks.

- packages/devtools-components/src/tests/tree.js
- packages/devtools-components/src/tree.css
- packages/devtools-components/src/tree.js
Fixes #691.
Adds a data-expandable attribute to the tree node that we
then target to show a pointer cursor only on expandable nodes.
> Don't show pointer cursor on Tree node if it is not expandable.

- packages/devtools-reps/src/object-inspector/tests/utils/node-has-all-entries-in-preview.js
- packages/devtools-reps/src/object-inspector/utils/node.js
Fixes #681.
Some Map grip can have a preview object which contains only a size property.
In such case, the ObjectInspector was throwing in `nodeHasAllEntriesInPreview`,
since it expected to have at least an entries or items property.
We now return early on the function if the preview object does not have an
entries nor an item property.
> Guard nodeHasAllEntriesInPreview

- packages/devtools-reps/src/reps/rep-utils.js
- packages/devtools-reps/src/reps/tests/string.js
It makes sense to pass through the Unicode replacement character,
because users understand it.  However, the other specials (including
unassigned ones) should be quoted.
Fixes #644
> Don't escape the Unicode replacement character

- packages/devtools-reps/src/reps/string.js
- packages/devtools-reps/src/reps/tests/string-with-url.js
This boolean prop prevents the creation of the href attribute on
generated links in the String rep. It is true by default so
consumer can use the String rep safely. We still want to be
able to generate the href attribute (for the JSON panel for example),
this is why we offer the choice to still create it.
Tests are added to make sure we don't regress.
> Add an omitLinkHref prop to the String rep.

- packages/devtools-source-map/src/tests/fixtures/noroot2.js
- packages/devtools-source-map/src/tests/fixtures/noroot2.js.map
- packages/devtools-source-map/src/tests/source-map.js
- packages/devtools-source-map/src/utils/fetchSourceMap.js
Currently _setSourceMapRoot bails if the source map contains all the
sources.  However, this is not valid according to the source map spec;
and the debugger doesn't work properly with the returned URLs.  On the
other hand, some source maps have non-URLs like "webpack:/bootstrap",
which we do want to treat as absolute.  So, this patch works around
the problem by examining the URLs in a mildly lax way.
Fixes #356
Associated Issue: #<issue number>
* change 1
* change 2
Tell us a little a bit about how you tested your patch.
> Compute sourceRoot when only relative URLs are seen

- packages/devtools-components/src/tree.js
We were having an `onScroll` event that was making the console lag
if you had a large number of ObjectInspector in it.
None of the consumer of this Tree component take advantage of this
so let's remove it.
We might want to reintroduce some virtualization later, but maybe using
the IntersectionObserver instead, since we can have variable height items.
Also this PR breaks keyboard navigation, as if you navigate to an
off-canvas item you won't be scrolled. I think this was already broken for
variable height items though. This should be fixed in another PR
with keeping in mind that this tree is not meant to be used as the single
component of a container. At the moment, every consumer disable the
keyboard navigation, so we don't put anyone at risk.
> Unvirtualize the Tree component.

- packages/devtools-components/src/tests/tree.js
- packages/devtools-components/src/tree.js
This patch adds a proper id attribute to the tree nodes
so that the `aria-activedescendant` attribute links to an
actual element.
It also fixes the use of `wrapper.everyWhere` which except to be returned an assertion.
> Use aria-activedescendant properly.

- packages/devtools-launchpad/package.json
Move eslint and some related packages to devDependencies.  This avoids
an error from the license checker.
> Move eslint to devDependencies

- packages/devtools-components/src/tests/__snapshots__/tree.js.snap
- packages/devtools-components/src/tests/tree.js
- packages/devtools-components/src/tree.js
- packages/devtools-components/stories/tree.js
This patch re-establish the keyboard navigation on the
Tree. It handles the scroll position of the closest
scrollable parent so when a node is focused it is not
off-canvas.
This also fixes smaller keyboard navigation bugs and add
tests to make sure everything works as expected.
> Fix keyboard navigation on the Tree component.

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/index.js
- packages/devtools-launchpad/src/tools/tests/webpack.config.js
Fixes a case where `theme-body` was not present
> fix theme-body

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/components/Sidebar.css
- packages/devtools-launchpad/src/components/Sidebar.js
using the CSS url caused an MC linter to fail because it couldn't find the rocket svg asset.
I'd like to circle back to the launchpad and keep a lot of the assets from bundling w/ the debugger
> Switch rocket to svg

- packages/devtools-reps/src/object-inspector/tests/component/create-object-client.js
In this test, we check that the ObjectInspector does not throw if
the create object client has not the method we expect.
If the objectClient is faulty, we do use console.error to warn the
developer though, and those console calls are spamming the terminal
during the test, which can make you think that some tests are failing.
Here we override console.error so we have a saner output.
> Override console.error in create-object-client.

- circle.yml
jest is taking a lot of memory on CI which ends up by npm dying and tests failing.
Limiting the number of workers might help.
> limit jest to 2 workers on CI for devtools-reps tests

- packages/devtools-source-editor/src/utils.js
Removes an unused function, that is now defined in debugger.html
> Remove resizeBreakpointGutter

- packages/devtools-map-bindings/src/tests/__snapshots__/updateScopeBindings.js.snap
- packages/devtools-map-bindings/src/tests/updateScopeBindings.js
- packages/devtools-map-bindings/src/updateScopeBindings.js
Associated Issue: blocks https://github.com/devtools-html/devtools-core/pull/780 and https://github.com/devtools-html/debugger.html/pull/4521
* Moves updateScopeBindings to the devtools-core
> Moves updateScopeBindings from debugger.html.

- packages/devtools-map-bindings/src/parser.js
Associated Issue: https://github.com/devtools-html/debugger.html/pull/4591
* Specifies some type info for Object.create(null)
> Specify type for Object.create(null)

- packages/devtools-utils/package.json
- packages/devtools-utils/src/worker-utils.js
We made the worker util reject tasks that were completed after the worker had shutdown a couple months ago. This rationale was so that tests that involved async behavior would strictly have to wait for the activity to complete before shutting down.
This was a mistake because our actions are going to be complex. It is therefore an implementation detail what work will follow an action and a test that is just looking at one action should not have to know it.
> NOTE this is just for our tests. the workers never shutdown during the lifetime of the app.
> Soften utils

- packages/devtools-source-editor/src/source-editor.js
#Associated Issue: no issues, required to add syntax highlighting for non js languages to better accommodate growing WASM support
* Added clike and rust modes to codemirror based source editor
No test plan as no changes to the features are implemented
n/a
> add clike and rust modes to source editor

- packages/devtools-reps/src/launchpad/components/Result.js
- packages/devtools-reps/src/reps/function.js
- packages/devtools-reps/src/reps/reps.css
- packages/devtools-reps/src/reps/tests/function.js
- packages/devtools-reps/src/shared/images/Svg.js
- packages/devtools-reps/src/shared/images/jump-definition.svg
Fixes #640.
The Function rep would accept an onViewSourceInDebugger prop, and the
icon would be shown when we do have this props as well as a location with
a non-null url (so we don't show it on prototypes for example).
Clicking on the button would call the prop with the location object.
A test is added to make sure we handle the different possible cases.
Open the Reps test app and evaluate a function
> Add a button to jump to a function definition.

- packages/devtools-components/src/tests/tree.js
- packages/devtools-components/src/tree.css
- packages/devtools-components/src/tree.js
- packages/devtools-components/stories/tree.js
Because it takes a lot of time to compute on large tree.
It wasn't only the massive "background as a border", but the indent as well.
Without those 2 scrolling is quite fast.
Using multiple elements for the indent and border works quite well.
Here is 2 profiles, with and without the patch, scrolling through a tree of a thousand node with one expanded root.
In order to get consistent results, I triggered the scrolling with this code : 
```js
var index = 0;
function scrollNext() {
index = index + 40;
nodes[index].scrollIntoView();
if (index < nodes.length - 1) {
requestAnimationFrame(scrollNext);
}
}
scrollNext();
```
where `nodes` contains all the nodes of the tree.
Profile without patch:  https://perf-html.io/public/24499d1b8bcd2e67f5071a867b0c3823f2e6c289/calltree/?hiddenThreads=&range=1. …
> Do not use CSS custom property in Tree.

- packages/devtools-components/src/tree.css
- packages/devtools-components/stories/tree.js
We have to make the indent take the whole height of the node. since it is a inline-block element, we can't do it without flex.
Making the node a flex item does not show performance penalty with my snippet
> Fix border for variable height nodes.

- packages/devtools-modules/index.js
This is needed for the StackTrace component that is being ported to devtools-components
> Expose SourceUtils in devtools-modules

- packages/devtools-reps/src/reps/string.js
- packages/devtools-reps/src/reps/tests/string-with-url.js
Fixes #864.
I created a new bundle and made sure the JSON viewer now behaves as it should.
> Fix string with URL when passed member.open

- package.json
Fixes #857, by ommiting `-s` options. I'm not sure if they meant to add some
sort of functionality or they were accidental, but removing them fixed the errors
for me.
> Fix lint scripts error

- packages/devtools-reps/src/reps/rep-utils.js
Associated Issue: #842
- Does not assume that grips with an actor will be object grips with a class
- Does not access `type` nor `actor` properties if `noGrip === true`
- Removes a seemingly unnecessary case about String objects, there shouldn't be such kind of grip. And if this was necessary in the `noGrip === true` case, then I guess that Boolean, Number and Symbol objects should also be handled.
You can update stubs or whatever else once symbol actors are really added.
I modified added an actor to symbol grips and applied this patch to `devtools/client/shared/components/reps/reps.js`. Symbol values were properly displayed in the console.
> Allow symbol grips to have an actor

- packages/devtools-reps/src/reps/stubs/symbol.js
- packages/devtools-reps/src/reps/symbol.js
- packages/devtools-reps/src/reps/tests/symbol.js
This then can be used to retrieve the actor the node is representing.
For example, in the console we can use it in the context menu entry
to store an object as a global variable.
Associated Issue: #878
- Add an actor id data attribute on symbol rep
I added an actor to symbol grips and applied #874 and this patch to devtools/client/shared/components/reps/reps.js. The symbols could be stored as global variables.
I also tried it without symbol actors (which is the current behavior) and then `object.actor` is undefined and react just ignores it. So it's harmless if this lands before [bug 1424722](https://bugzilla.mozilla.org/show_bug.cgi?id=1424722).
> Add an actor id data attribute on symbol rep

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/state.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-entries.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-indexed-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-non-indexed-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-prototype.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-symbols.js
- packages/devtools-reps/src/object-inspector/utils/index.js
- packages/devtools-reps/src/object-inspector/utils/load-properties.js
- packages/devtools-reps/src/object-inspector/utils/node.js
This will allow a consumer (e.g. the debugger) to preload properties of a given root
and use them as it wishes (e.g., for the debugger, use all the direct properties as
root for the ObjectInspector of the Popup preview).
> [WIP] Move the logic to load properties of a node to util file.

- packages/devtools-license-check/bin/devtools-license-check
Zlib is used by the packo packages, which is a dependency of babel-eslint,
of which we need the latest version on the debugger.
The [Zlib license](https://spdx.org/licenses/Zlib.html) seems pretty safe to
add in the list of valid licenses here.
> Add Zlib into valid licenses.

- packages/devtools-connection/src/debugger/client.js
Rewinding can be used with tabs that are replaying via Web Replay, mozilla bug 1422587.
> Add ThreadClient methods for rewinding and reverse-stepping a thread.

- packages/devtools-components/src/tree.css
- packages/devtools-components/stories/tree.js
Fixes #886.
If a Tree contained multiple roots, some expandables, some not, the
non-expandable node weren't aligned to the expanded one.
This is because we align non-expandable items adding a margin to the
last tree-indent element of the node.
However, non-expandable root do not have any tree-indent element child,
so they were missing a margin.
This patch adds a specific margin-inline-start for non-expandable root nodes.
The multiple root tree story is modified to also include non-expandable root
nodes.
> Fix style for non-expandable root nodes in Tree component.

- packages/devtools-reps/src/index.js
This is needed for the debugger to be able to fetch properties on its own.
> Expose all ObjectInspector utils.

- packages/devtools-reps/README.md
I used relative links, so there seems no advantage to pinning the branch.
> Update README.md links

- packages/devtools-connection/src/webconsole/client.js
This PR add `getStackTrace` method for fetching stack-trace info from the back-end.  This method exists in m-c for some time, but wasn't synced with devtools-connection package.
Honza
> Introduce getStackTrace method for webconsole client (sync with m-c)

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/basic.js
Fixes #904.
Add a test to make sure we don't regress this.
> Flush nodes cache when roots prop is updated.

- packages/devtools-launchpad/webpack.config.js
This is useful for projects using the launchpad but with no need for postCSS (devtools-reps, console, netmonitor, …)
> Allow to disable postCSS loader

- packages/devtools-connection/src/debugger/client.js
Just a signature update, removing an unused and deprecated argument. Note that listTabs now supports an options object as first argument. However this is only available on Nightly and given that launchpad can connect to several versions of Firefox I don't think we should explicitly advertise it here.
options would allow launchpad to retrieve favicon data, which could be a nice addition to the list of tabs.
> Fix #917 - update listTabs API to remove deprecated callback argument

- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/properties.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/properties.js
- packages/devtools-reps/src/object-inspector/utils/node.js
Related Issues: #5252, #5215
* Adds `nodeIsUninitializedBinding` which I'm surprised wasn't already there. Uninitialized bindings were just showing as `null`, so this makes them show as `(uninitialized)`
* Adds two more states related to mapping original source file bindings to the actual executing bindings
> Add new representations for uninitialized/unmapped/unscoped.

- packages/devtools-utils/src/network-request.js
* The launchpad server does not support inline base64 URLs as well as the panel. 
* adding atob support here is an edge case that could be a bit faster.
here is a patch for adding it to the [launchpad ](https://github.com/devtools-html/devtools-core/compare/master...jasonLaster:network-req?expand=1). unfortunately, here node does not send the mappings down well in every case...
> decode base64 inline json

- packages/devtools-splitter/src/SplitBox.js
In conjunction with this PR to debugger: https://github.com/devtools-html/debugger.html/pull/5383
* force a state change when changing the initial measurements
This is to ensure that when we render another SplitBox in the same location, it actually get initialized as desired.
Another solution could be to use react's `key` property, perhaps passed into props, so that react can tell that it is a different element.
> force a state change when changing the initial measurements

- packages/devtools-launchpad/src/index.js
Associated Issue: #846
- added check if debugged target exists
- if not we default to launchpad
- tested on running debugger
> Opens launchpad on reload of previously closed external tab

- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/stubs/grip.js
- packages/devtools-reps/src/reps/tests/grip.js
It was already picked up, but because the GripRep is the default rep we fall
back to when no other Rep support the object.
Adding a test (and a stub) to make sure we handle those object as expected.
> Add explicit support for DeadObject in Grip rep.

- packages/devtools-reps/src/reps/document.js
- packages/devtools-reps/src/reps/stubs/document.js
- packages/devtools-reps/src/reps/tests/document.js
Add a stub and a test to make sure we don't regress this.
Fixes #933.
And fixes https://bugzilla.mozilla.org/show_bug.cgi\?id\=1438454 as well
> Handle XULDocument in the Document rep.

- packages/devtools-launchpad/src/server/launch.js
Associated Issue: #749
* launch chrome with `node` as first arguments, since windows don't know about shebag notation
* catch error if selenium driver throw ff not found
* Not bump version since, doesn't have credentials to do so
* No test
Tell us a little a bit about how you tested your patch.
Still looking where the existing test :cold_sweat:
> Fix launching chrome on windows

- packages/devtools-reps/package.json
See [Bug 1436670](https://bugzilla.mozilla.org/show_bug.cgi?id=1436670).
[TRY run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=69a07dcf5a90d892ca084777f3b05f70db61ebd7)
> [WIP] Bump devtools-reps to 0.20.0

- packages/devtools-launchpad/bin/firefox-proxy
The console message shows the wrong property name.
> Fix console message explaining how to turn on logging.

- packages/devtools-components/src/images/arrow.svg
- packages/devtools-reps/src/shared/images/jump-definition.svg
- packages/devtools-reps/src/shared/images/open-inspector.svg
Fixes #950.
The attribute is removed by React anyway, and it prints a warning message in
the console
> Remove xmlns attribute in svgs.

- packages/devtools-reps/src/reps/document-type.js
- packages/devtools-reps/src/reps/grip.js
- packages/devtools-reps/src/reps/rep.js
- packages/devtools-reps/src/reps/stubs/document-type.js
- packages/devtools-reps/src/reps/tests/document-type.js
Fixes #945.
Previously it was rendered by the Grip Rep and was causing issue
because the packet does not have a ownProperties prop.
Adding a dedicated Rep, with similar output as in the markup view fixes
the issue. Stubs and tests are added as well.
And to be safe, we default ownProperties to an empty object in the Grip
rep so we don't have errors anymore.
We don't have the data in the packet to show the dtd, this will be done as a follow up
> Add DocumentType rep.

- packages/devtools-launchpad/configs/development.json
- packages/devtools-launchpad/src/server/launch.js
It was hardcoded in launch.js and was well suited for the debugger,
but other tools might want to see other default pages.
> Move the url opened when clicking the launch firefox button to config

- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/utils/selection.js
The issue was caused because of the documentHasSelection helper
we introduced recently.
When an inline svg document is clicked, the getSelection does return
a Range type.
Here we set an explicit if for the arrow click to fix the issue.
> Expand node when arrow is clicked

- packages/devtools-reps/package.json
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/window.js.snap
- packages/devtools-reps/src/object-inspector/tests/test-utils.js
- packages/devtools-reps/yarn.lock
Some snapshots are updated since the tree was modified (aria-level),
and formatObjectInspector is updated to address this.
> Use devtools-components-0.3.0 in devtools-reps.

- packages/devtools-reps/src/reps/error.js
- packages/devtools-reps/src/reps/stubs/error.js
- packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap
- packages/devtools-reps/src/reps/tests/error.js
Fixes #971.
Extract stacktrace creation into its own function and strip base-loader part if needed
> Strip browser-loader part in frames url for the Error rep stacktrace

- packages/devtools-reps/src/reps/error.js
- packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap
Fixes #959.
Built on top of https://github.com/devtools-html/devtools-core/pull/973, only https://github.com/devtools-html/devtools-core/commit/4c4accc965f9a9f233ce2837b956aaed10600d0f is relevant here.
- Display `<anonymous>` for unnamed functions.
- Call cleanFunctionName on it.
>  Better function name in Error stacktrace. 

- packages/devtools-reps/src/object-inspector/index.css
Changes suggested by @violasong 
Here's how it looks :
> Tweak ObjectInspector node block styling.

- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/entries.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/expand.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/proxy.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/basic.js
- packages/devtools-reps/src/object-inspector/tests/component/entries.js
- packages/devtools-reps/src/object-inspector/tests/component/expand.js
- packages/devtools-reps/src/object-inspector/tests/test-utils.js
- packages/devtools-reps/src/object-inspector/tests/utils/get-children.js
- packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-indexed-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-non-indexed-properties.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-prototype.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-symbols.js
- packages/devtools-reps/src/object-inspector/utils/node.js
`__proto__` is renamed to `<prototype>` and
`[default properties]` is renamed to `<default properties>` so
all our pseudo nodes share the same syntax, i.e. `<${name}>`.
> Have consistent pseudo-nodes in ObjectInspector.

- packages/devtools-reps/src/reps/rep-utils.js
- packages/devtools-reps/src/reps/string.js
- packages/devtools-reps/src/reps/tests/string-with-url.js
- Only rely on openLink prop function
- Do not linkify `javascript:` urls
> Remove omitLinkHref prop and never populate the href attribute

- packages/devtools-reps/src/object-inspector/index.js
This was causing a leak in a mochitest in mozilla-central.
> Don't use a closure to expose the ObjectInspector store.

- packages/devtools-reps/src/object-inspector/actions.js
- packages/devtools-reps/src/object-inspector/reducer.js
- packages/devtools-reps/src/object-inspector/utils/load-properties.js
The function was deleted in https://github.com/devtools-html/devtools-core/commit/7c538787e1f19c07e868192268097f6c8845feb2\#diff-1d5a77fb4120fb410c4af9fa9a4eb936
because it wasn't used in devtools-reps code.
But it was exported and the debugger does use it for
the Preview popup.
So we re-create it and make sure the similar action use
it as well so the ObjectInspector and debugger code path
don't diverge.
---
tested both in devtools-reps' launchpad and debugger.html (cp'ed)
> Re-create loadItemProperties function which is used by the debugger.

- packages/devtools-reps/src/object-inspector/component.js
- packages/devtools-reps/src/object-inspector/index.js
- packages/devtools-reps/src/object-inspector/tests/component/basic.js
- packages/devtools-reps/src/object-inspector/tests/utils/should-render-roots-in-reps.js
- packages/devtools-reps/src/object-inspector/utils/index.js
When we have a single primitive root, there's no advantage rendering
them inside the ObjectInspector component. On the contrary, it adds
some overhead that can harm performances.
This patch allow us to branch early so we don't go through the ObjectInspector
element if we don't need to.
> Do not create an ObjectInspector element for primitive grips.

- packages/devtools-reps/src/object-inspector/tests/utils/should-render-roots-in-reps.js
- packages/devtools-reps/src/object-inspector/utils/index.js
- packages/devtools-reps/src/object-inspector/utils/node.js
Fixes #960.
Since the ErrorRep already provides all the error informations
in a nice way (message and stacktrace), there's no benefits
being able to inspect the object. Furthermore, when in the console,
throwing an Error object gives you a double arrow (first to expand
the stack we get from the exception, second is the objectInspector
arrow), which is clearly not ideal.
Using Rep directly solves these issues.
> Don't use ObjectInspector for Error grips.

- packages/devtools-source-map/src/index.js
- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/utils/index.js
- packages/devtools-source-map/src/worker.js
Related Issue: #5561
* Expose `allGeneratedPositionsFor` from consumer
* Mark `.mjs` files as JavaScript.
> Expose the consumer's 'allGeneratedPositionsFor' method in the worker

- packages/devtools-launchpad/README.md
- packages/devtools-launchpad/src/components/Settings.js
- packages/devtools-launchpad/src/index.js
- packages/devtools-reps/src/reps/reps.css
Synchronization from https://bugzilla.mozilla.org/show_bug.cgi?id=1378108
Fixes Issue: #1025
* removed references to firebug in reps css files
* removed references to firebug in launchpad UI
I kept the screenshots showing the Firebug theme (eg. in issues.md), felt overkill to recreate screenshots just for that.
> Remove firebug theme

- packages/devtools-reps/src/object-inspector/component.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/expand.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/expand.js
- packages/devtools-reps/src/object-inspector/utils/selection.js
Fixes #1017.
Since clicking on the arrow does NOT unselect potential selected
text, we need to check the target of the click and see if it is
the node arrow. In such case, we don't block the expansion.
---
A mochitest will be added in mozilla-central to be sure it does work with "true" text selection (in Node we can only rely on a mock)
> Fix expanding node with selected text.

- packages/devtools-reps/src/launchpad/components/Result.js
- packages/devtools-reps/src/object-inspector/component.js
- packages/devtools-reps/src/object-inspector/index.css
- packages/devtools-reps/src/object-inspector/reducer.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/entries.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/expand.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/keyboard-navigation.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/window.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/keyboard-navigation.js
- packages/devtools-reps/src/object-inspector/tests/test-utils.js
- packages/devtools-reps/yarn.lock
The fix here is mainly to call the nodeFocus action when needed in order to changed the `focusedItem` state value.
Also, we let the Tree component handle the call to setExpanded (through `onExpand` and `onCollapse` props), and only stop the propagation of the click event on a tree node for the text selection case.
The objectInspector test formatter was modified in order to reflect whether a node is selected or not, and as a result snapshots were updated.
A simple keyboard navigation test is added to test the basic. I didn't added to many case since this is also tested in the Tree component, and I will add keyboard navigation tests in consumers (at least for the webconsole, and we should also do it in the debugger)
> Fix ObjectInspector keyboard navigation

- packages/devtools-source-map/src/index.js
- packages/devtools-source-map/src/source-map.js
- packages/devtools-source-map/src/worker.js
- packages/devtools-utils/src/tests/worker-utils.js
- packages/devtools-utils/src/worker-utils.js
Associated Issue: https://github.com/devtools-html/debugger.html/issues/5561
* Allow multiple synchronous calls to an async task to be batched into a single postMessage
* Add a new function for getting the generated ranges for a given original location
> Allow batched worker tasks and generated sourcemap range lookup

- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/basic.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/entries.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/expand.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/getter-setter.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/keyboard-navigation.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/properties.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/proxy.js.snap
- packages/devtools-reps/src/object-inspector/tests/test-utils.js
This way tree nodes in snapshot are well aligned.
> Wrap text representation of ObjectInspector in new lines.

- packages/devtools-components/src/tests/__snapshots__/tree.js.snap
- packages/devtools-components/src/tests/tree.js
- packages/devtools-components/src/tree.js
Fixes #923
- Adds keyboard shortcut to navigate to first and last opened nodes (<kbd>Home</kbd>/<kbd>End</kbd>)
- Adds an `onActivate` prop, called with the focused item when <kbd>Enter</kbd>
- Fix `scrollNodeIntoView` function (always use boundingClientRect to determine if a node is visible or not).
> Tree component fixes and improvements

- .flowconfig
- packages/devtools-reps/src/object-inspector/actions.js
- packages/devtools-reps/src/object-inspector/component.js
- packages/devtools-reps/src/object-inspector/reducer.js
- packages/devtools-reps/src/object-inspector/store.js
- packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/basic.js.snap
- packages/devtools-reps/src/object-inspector/tests/component/basic.js
- packages/devtools-reps/src/object-inspector/tests/component/release-actors.js
The roots prop isn't handled by the redux state, but is passed from
upper-level components (e.g. console, inspector, ...). There might be
cases when the roots prop changes (e.g., in the console, the object sidebar
is already opened, and the user choose to put another object in it).
In such cases, there are a few things that should be taken care of:
- we need to clear the node cache to start anew
- we need to clean the redux state of the old roots-related properties,
like expandedPaths, loadedProperties, …
- we need to release the actors related to the old roots.
- we need to make sure a possible new focusedItem is handled as expected.
In order to do that, we create a rootsChanged action that's handled in
a middleware where we reinitialize the state and release actors.
We don't want to …
> Cleanup redux state when roots prop changes.

- packages/devtools-reps/src/object-inspector/utils/client.js
When expanding a node, in some cases, we query the server to know how
much indexed, non-indexed and symbol properties we have in the object.
The issue is that we then always try to get all the properties of the
object, even if the server told us there was none.
This patch prevent this and should save a couple of client-server round-trip.
> Prevent unnecessary server call when expanding node.

- packages/devtools-reps/src/object-inspector/utils/node.js
Lodash functions were used in an hot function and was taking significant amount of
time (~80ms). Using plain js does not make the code too bad and shaves of dozens of
millisecond (~25ms).
> Remove lodash usage from ObjectInspector util.

- packages/devtools-connection/src/debugger/client.js
- packages/devtools-reps/src/object-inspector/utils/node.js
- packages/devtools-reps/src/reps/grip-map-entry.js
The changes here are harmless and don't depend upon the patch from https://bugzil.la/1454103
We were sometimes missing keys on local and session storage because we were trying to iterate over these special objects using the wrong methods.
This patch along with the bugzilla patch allow us to display the storage types entries in a similar way to a map or sets entries are displayed.
> Added changes use local/sessionStorage objects in object actor

- packages/devtools-modules/index.js
- packages/devtools-modules/package.json
- packages/devtools-modules/src/tests/unicode-url.js
- packages/devtools-modules/src/unicode-url.js
See also
https://bugzilla.mozilla.org/show_bug.cgi?id=1454910
and
https://github.com/devtools-html/debugger.html/issues/5977
This patch introduces the unicode-url shim and the test for it.
> Introduces unicode-url shim

- packages/devtools-reps/src/launchpad/components/Result.js
- packages/devtools-reps/src/object-inspector/component.js
- packages/devtools-reps/src/object-inspector/tests/component/events.js
- packages/devtools-reps/src/object-inspector/types.js
This will be called with the item an data about it when
the user Ctrl + Click (Cmd on OSX) on a node.
This will be useful in the console in order to have a shortcut
to put objects in the sidebar.
> Add an onCmdCtrlKey prop to the ObjectInspector.

- packages/devtools-components/src/tree.js
The scrollNodeIntoView function is called from the _focus function,
which can be called either when the user navigate via the keyboard,
or when a user click a node.
When navigating with the keyboard, it makes sense because we might
focus a node which isn't visible on the viewport so we need to scroll
it into view.
When clicking a node, obviously it is already visible (unless we call
node element.click , but that's never done in the code). Because it's
already visible, no need to check if we should scroll, so we save
the computation time.
Dealing with focus/scrolling in jest test is hard, I'll create mochitest in mozilla-central to make sure this is working as expected (we already have a jest test that ensure that clicking a tree node focus it).
> Prevent _scrollNodeIntoView click on Tree node click.

- packages/devtools-reps/src/reps/rep-utils.js
The function was splitting up a string and testing if each parts was an actual URL,
until one was encountered.
The split function was showing up in some profile I did today (nothing too big, but
bigger that it should be).
Here switching to a simple regex test works and is faster to run.
> Speed up containsURL function.

- packages/devtools-reps/src/object-inspector/component.js
- packages/devtools-reps/src/object-inspector/tests/component/events.js
- packages/devtools-reps/src/object-inspector/types.js
In the end, `this.focusItem` checks `disabledFocus`, so it's not too bad. But the Tree component might use the presence of `onFocus` to do extra work. Let's avoid that.
> Don't pass onFocus prop to Tree if disabledFocus is true

- packages/devtools-utils/src/worker-utils.js
Fixes #1055
I didn't "move" the `if (this.worker)` as mentioned in the issue summary, since the one located below is in a callback that might be invoked at a different time, but just added another one before calling `this.worker.postMessage`.
> Guard against null worker in /devtools-utils/src/worker-utils.js

- packages/devtools-environment/index.js
- packages/devtools-environment/package.json
- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/development-server.js
- packages/devtools-launchpad/src/index.js
- packages/devtools-launchpad/src/utils/debug.js
- packages/devtools-launchpad/yarn.lock
- devtools-environment should use commonjs
- devtools-launchpad should use devtools-environment
> Upgrade devtools-launchpad to new environment

- packages/devtools-launchpad/webpack.config.js
For https://github.com/devtools-html/debugger.html/pull/6595, we need babel to still compile react-aria-components.
As a part of that, this slightly refactors how the regex doing the matching is constructed.
> Allow Configuration of Packages to Process

- packages/devtools-splitter/src/SplitBox.css
Associated Issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1465644
* Change the size of SplitBox min-height or min-width.
- I added 1px extra width to the splitter of m-c and renamed the related variable.
* Change the background color of the SplitBox.
* Add hover style to the splitter.
This commit changes the style only.
> Change the splitter's variable name since m-c has changed these name.

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/development-server.js
Associated Issue: #1080
* use Buffer instead of string's +=
* report mime type into account
> Return unaffected binary content and provide mime on /get endpoint

- packages/devtools-contextmenu/menu.js
- packages/devtools-modules/src/menu/index.js
In the toolbox, it might happen that window is not defined.
Guarding the inToolbox with should be enough to identify an
environment as toolbox or not.
> Modify inToolbox function.

- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/src/development-server.js
- packages/devtools-launchpad/yarn.lock
Associated Issue: #1091 
* Upgrade `check-node-version` to latest version (^3.2.0)
* Fixed `checkNode` call: it expects an object, not a string.
Link this version of devtools-launchpad to debugger.html
```
cd devtools-core/packages/devtools-launchpad
yarn link
cd debugger.html
yarn link devtools-launchpad
```
Launch debugger.html with the command `yarn start`.
**Expected result:** if you have a version of node gte than 7.0.0, server starts.
Change for a moment the minimun node version required in devtools-launchpad's package.json to something very big (such as 42).
**Expected result:** process exits with an informative error message.
> Launchpad incorrect check node

- packages/devtools-contextmenu/package.json
- packages/devtools-contextmenu/yarn.lock
- packages/devtools-launchpad/package.json
- packages/devtools-launchpad/yarn.lock
- packages/devtools-modules/package.json
- includes a necessary devtools-modules version bump
- changes devtools-modules and devtools-contextmenu to 1.0.x versioning, which will let us bump one of these packages without having to change the version of a package that depends on it
> Bump devtools versions

- packages/devtools-launchpad/package.json
We'll need this update so we can use setXhrBreakpoint in the debugger.
> Bump version of connection in launchpad

- packages/devtools-modules/src/menu/index.js
Related to XUL removal.
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1476097
Honza
> Popupset element for context-menu doesn't have to exist

- packages/devtools-connection/src/debugger/client.js
To support blackboxing original sources, we use ranges in generated source. 
Parent PR: https://github.com/devtools-html/debugger.html/pull/7370
> Modify blackbox signature to support ranges

- packages/devtools-launchpad/src/index.js
Fixes:
- https://github.com/firefox-devtools/debugger/issues/8164
- https://github.com/firefox-devtools/debugger/issues/7904
At least once we update devtools-core there.
In standalone ("dev") mode, move the platform attribute and `theme-(light|dark)` class to the :root element (document.documentElement), matching the DOM structure in the Firefox DevTools Debugger panel.
I tested from Debugger by running:
```
$ yarn
$ cp ../devtools-core/packages/devtools-launchpad/src/index.js node_modules/devtools-launchpad/src/index.js
$ yarn start
```
And checking the result visually and with the Inspector.
> Launchpad - in dev, move platform attr to documentElement to match firefox panel

- packages/devtools-launchpad/src/development-server.js
Webpack accepts arrays of configs along with single objects, so the dev server should too.
> Handle the possibility of multiple Webpack configs.

- packages/devtools-launchpad/bin/firefox-driver.js
- packages/devtools-launchpad/src/components/LandingPage.js
- packages/devtools-launchpad/src/components/Sidebar.js
Changed the launchpad so that it launches Firefox to Firefox Nightly. Only updated the bare minimum (display text for launch button and sidebar) so that it's easy to revert when we can use Firefox stable again.
I've checked that it works on Mac, but keeping this as draft as I haven't tested this on Windows yet.
<details><summary><strong>GIF: Launching Firefox Nightly from Launchpad</strong></summary>
</details>
<br>
<details><summary><strong>GIF: Switching between Sidebar tabs</strong></summary>
</details>
> Switch from launching Firefox to Firefox Nightly

- packages/devtools-connection/src/debugger/client.js
Fixes [8178](https://github.com/firefox-devtools/debugger/issues/8178).
Added a `skipBreakpoints` method to the ThreadClient prototype.
1) Copy the modified `client.js` to `debugger/node_modules/devtools/connection/src/debugger`
2) Run the debugger from launchpad
3) Open TodoMVC, set and trigger a breakpoint to check that breakpoints are being paused on
4) Enable skip breakpoints by pressing the "Deactivate Breakpoints" button
5) Check that the breakpoints are no longer paused on
6) Check the console to make sure the error `threadClient.skipBreakpoints is not a function` no longer persists
> Added skipBreakpoints method to ThreadClient

- packages/devtools-contextmenu/menu.js
- packages/devtools-modules/src/menu/index.js
Menu API should now take a document argument and there is additional logic to hide the context menu when its parent window is hidden.
The corresponding bugzilla record is https://bugzilla.mozilla.org/show_bug.cgi?id=1543940
It is a mandatory change to run DevTools in frame with type=content (https://bugzilla.mozilla.org/show_bug.cgi?id=1539979) which is required for the overall fission effort.
> Synchronize context menu changes needed for Bug 1543940

- packages/devtools-contextmenu/menu.js
- packages/devtools-modules/index.js
This will allow us to add two mappings to mozilla-central-mappings:
```javascript
"devtools-modules/src/menu": "devtools/client/framework/menu",
"devtools-modules/src/menu-item": "devtools/client/framework/menu-item",
```
After this change, the debugger will use the regular menu implementation when running in the toolbox.
There is a lot of cleanup possible between devtools-contextmenu and devtools-modules/src/menu after that, since they are only used when running in content, but I'd leave that for later.
> Require Menu and MenuItem with full path to override for mc bundle

- packages/devtools-contextmenu/menu.js
- packages/devtools-modules/src/menu/index.js
Sync with https://bugzilla.mozilla.org/show_bug.cgi?id=1552444
"about:devtools-toolbox" is only valid for the default toolbox. We can also have additional parameters to modify the target, the runtime etc...
> Fix inToolbox helpers to detect about:devtools-toolbox URLs

- packages/devtools-modules/index.js
- packages/devtools-modules/src/plural-form.js
Associated Issue: 
Regarding revision for: https://phabricator.services.mozilla.com/D32881
Jason, you mentioned a simplified version of the plural-form file.
It is easier to keep the functionality of the original plural form module because of the arguments it accepts. PluralForm.get needs the string value (ex. #1 result;#1 results) instead of the key (ex. sourceSearch.resultsSummary2). We calculate and store the string value anyway in our debugger components that use PluralForm so we can just use the function the same way in Launchpad, which means we can pluralize there too. 
Thanks!
> Add plural form module to devtools-modules

- packages/devtools-services/index.js
This is needed for the console mocha test on a new patch that adds https://searchfox.org/mozilla-central/rev/17756e2a5c180d980a4b08d99f8cc0c97290ae8d/devtools/shared/flags.js as a dependency (which makes use of `Services.obs`).
I tried to make this approximately correct, but didn't spent too much time in there.
> Add an ObserverService on Services.obs

- packages/devtools-modules/src/source-utils.js
- packages/devtools-modules/src/tests/source-utils.js
As https://bugzilla.mozilla.org/show_bug.cgi\?id\=1519103 will land
soon, we don't need to deal with Scratchpad anymore.
> Remove references to Scratchpad.

- packages/devtools-modules/package.json
1.1.7 was published but the version number  change wasn't commited :/
> Bump devtools-modules to 1.1.8

- packages/devtools-contextmenu/package.json
We simply require the newest version of devtools-modules.
Jumping to 1.0.13 as there's already a 1.0.12 version published.
> Bump devtools-contextmenu to 1.0.13.

- packages/devtools-launchpad/package.json
We simply require the latest devtools-contextmenu.
Jumping directly to 0.0.159 because 158 was already
published.
> Bumping launchpad to 0.0.159.

- packages/devtools-launchpad/package.json
We simply require the latest devtools-contextmenu.
> Bumping launchpad to 0.0.160.

- packages/devtools-license-check/bin/devtools-license-check
I found these (invalid) values in some existing packages that we use, some of them transitively, in the profiler server. This would be a bit painful to make them all update...
> Add a few more aliases for MPL2 and Apache 2
