package.json, packages/devtools-client-adapters/src/chrome/commands.js, packages/devtools-client-adapters/src/chrome/events.js, packages/devtools-client-adapters/src/tcomb-types.js, packages/devtools-local-toolbox/package.json, yarn.lock
related to:
https://github.com/devtools-html/debugger.html/pull/1435
=> Add support for chome scopes

packages/devtools-launchpad/package.json, packages/devtools-launchpad/webpack.config.js
Forked to go off of the github version, which was messing up.
=> Fork single module instance

packages/devtools-launchpad/index.js, packages/devtools-launchpad/src/tools/index.js, packages/devtools-launchpad/src/tools/mc/README.md, packages/devtools-launchpad/src/tools/mc/make-bundle.js, packages/devtools-launchpad/src/tools/mc/symlink-tests.js, packages/devtools-launchpad/src/tools/utils/copy-file.js, packages/devtools-launchpad/src/tools/utils/process-handler.js
* copyFile
* symlinkTests
* ...
=> Add MC utilities

packages/devtools-client-adapters/package.json, packages/devtools-launchpad/index.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/webpack.config.js
cc @jasonLaster 
Here's a WIP to enable using symlink for launchpad w/ debugger.html
=> support symlink development mode

packages/devtools-launchpad/src/components/LandingPage.css, packages/devtools-launchpad/src/components/LandingPage.js
We simplify the rendered markup and some of the logic of the render function.
This allows us to also simplify the CSS, by mostly using the capabilities of
flexbox to have the same UI as we had before (no absolute positionning).
We also add some custom properties so the styling is more consistent.
=> Better styling on the landing page

packages/devtools-launchpad/.storybook/config.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/src/components/LandingPage.js, packages/devtools-launchpad/src/components/LaunchpadApp.js, packages/devtools-launchpad/src/index.js, packages/devtools-launchpad/stories/index.js
I started a storybook integration but faced two issues so let's discuss.
1. had to move the Redux related code out of the LandingApp component. Using storybook with Redux seems feasible but complicated, not sure it's worth the investment
2. feature.js would fail on Chrome when trying to export its methods (getValue is undefined). Not sure what's up with that, might be linked to the default webpack config used by storybook
cc @jasonLaster ; will try to investigate more the last issue mentioned above
=> Add storybook to test LandingPage component

packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/index.html
=> This makes DIR configurable

packages/devtools-client-adapters/src/firefox/commands.js, packages/devtools-modules/client/shared/components/reps/grip.js
These updates are around edge cases found in watch expressions
=> Small updates for watch-expressions

packages/devtools-launchpad/src/components/LandingPage.js
Fixes #47
Tested by running `yarn run storybook` and checking that each link works for Fx, Chrome, and Node.
=> update the docs link

packages/devtools-client-adapters/src/chrome.js
This should fix https://github.com/devtools-html/debugger.html/issues/502
=> close connection with beforeunload handler

packages/devtools-launchpad/bin/development-server.js
=> Handle https requests in development-server.js

packages/devtools-modules/client/shared/components/splitter/SplitBox.js
Fixes https://github.com/devtools-html/debugger.html/issues/1564
=> Don't render side panels when collapsed.

bin/install-yarn, circle.yml
This adds a pretty simple CI script based off of the debugger's [circle config](https://github.com/devtools-html/debugger.html/blob/master/circle.yml)
Goals:
* install top level npm deps
* run eslint
* run stylelint
Here's the [ci tracking issue](https://github.com/devtools-html/devtools-core/issues/61) for a more complete list of tasks
r? @tromey, @juliandescottes, @janodvarko
=> Adds Circle

packages/devtools-sham-modules/client/shared/key-shortcuts.js
Fixes: https://github.com/devtools-html/debugger.html/issues/1501
=> Fix shortcut key mapping.

packages/devtools-launchpad/bin/chrome-driver.js
Issue #86 
Allows  doing `yarn run chrome`load the browser with  a url
=> Enable loading chrome with url to go to

packages/devtools-sham-modules/shared/webconsole/network-helper.js
Pulls in the change from m-c
https://bugzilla.mozilla.org/show_bug.cgi?id=1331081
=> Update network helper

packages/devtools-client-adapters/src/types.js, yarn.lock
Associated Issue: https://github.com/devtools-html/debugger.html/pull/1737
1. Add missing export types that are used in the associated issue.
=> Add missing export types

packages/devtools-launchpad/src/tools/mc/make-bundle.js
This allows the script to be ran in Windows where it currently is failing for whatever reason.
**Warning** I've only done the most superficial test of using yarn to link to reps and running reps install to see if I got the site to run after doing `yarn start`. Beyond that, I really have no idea what to look for to verify this is working as it was before.
=> Use webpack Node api over creating system process

packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/src/components/LandingPage.css, packages/devtools-launchpad/src/components/LandingPage.js
Associate Issue: #70 
* Added launch buttons for firefox and chrome
*
=> Browser launch button

packages/devtools-launchpad/package.json
Let's fix this npm page once and for all!
Shamelessly took the sentence from the readme.md
=> add description to package.json to fix npm page display

packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/src/components/LandingPage.css, packages/devtools-launchpad/src/components/LandingPage.js
Associated Issue: #37
This is a first pass at the settings pane. Did a bit of cleanup based of the pairing work with @jasonLaster @jbhoosreddy 
This is just read only mode, and we just pulling `dlr` and `theme` settings.
CC @jasonLaster
=> Settings panel

.gitignore
if it's alright, I'd like to add common IDEs to gitignore as we did in debugger.html repo.
=> add common IDEs to gitignore

packages/devtools-config/src/feature.js, packages/devtools-launchpad/src/components/LandingPage.css, packages/devtools-launchpad/src/components/LandingPage.js
Associated Issue: #133 
devtools-launchpad: Adds features in Settings Page.
devtools-config: Modified logic for feature checking
=> [Settings] add features

packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/bin/firefox-driver.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/src/components/LandingPage.js, packages/devtools-launchpad/yarn.lock
#116, #132 
* support symlinking devtools-launchpad
* launch examples
* fix refresh bug
* only open one firefox
CC @bomsy
=> Some launchpad updates

packages/devtools-client-adapters/src/chrome.js, packages/devtools-client-adapters/src/chrome/commands.js, packages/devtools-client-adapters/src/chrome/create.js, packages/devtools-client-adapters/src/chrome/events.js, packages/devtools-client-adapters/src/types.js
This adds a couple utilities for fetching local properties and other scope and object properties from chrome.
The work came out of our community call.
=> Support loading chrome scopes and variables

packages/devtools-client-adapters/package.json, packages/devtools-config/package.json, packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
Associated PR: #136 
Need to bump version to enable reading on new schema.
=> version bump for schema change

package.json
=> Remove semicolon causing issues for git bash on Windows.

packages/devtools-client-adapters/src/firefox/commands.js, packages/devtools-client-adapters/src/firefox/types.js
Associated Issue: https://github.com/devtools-html/debugger.html/pull/1886
- Refactor `getSources` and add `SourcesPacket` type
=> Refactor for devtools-html/debugger.html#1886

lerna.json, packages/devtools-launchpad/src/lib/themes/common.css, packages/devtools-launchpad/src/lib/themes/dark-theme.css, packages/devtools-launchpad/src/lib/themes/light-theme.css, packages/devtools-launchpad/src/lib/themes/variables.css
Associated Issue: devtools-html/debugger.html#1400
* Add gutter background color
* Remove right border
|Light|Dark|Firebug|
|-|-|-|
|![light](https://cloud.githubusercontent.com/assets/1755089/22512184/2250d456-e8be-11e6-8f78-6973bbaae68b.png)|![dark](https://cloud.githubusercontent.com/assets/1755089/22512192/2889837c-e8be-11e6-9a8e-bc2b7bb8f2fc.png)|![firebug](https://cloud.githubusercontent.com/assets/1755089/22512207/2ebb6350-e8be-11e6-8d6f-068feeb3e76b.png)|
I tried adding right-padding but it resizes gutter width. Let me know what you think.
EDIT:
Screenshots with breakpoints
|Light|Dark|Firebug|
|-|-|-|
|![light_breakpoint](https://cloud.githubusercontent.com/assets/1755089/22515675/4b4d474e-e8c9-11e6-9883-f23e39650c23.png)|![dark_breakpoint](https://cloud.githubusercontent.com/asse …
=> Remove gutter border and add background color

packages/devtools-launchpad/bin/firefox-driver.js
Small fix. The path module includes this already.
=> use path.delimiter

packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/src/actions/config.js, packages/devtools-launchpad/src/actions/types.js, packages/devtools-launchpad/src/components/LandingPage.js, packages/devtools-launchpad/src/components/LaunchpadApp.js, packages/devtools-launchpad/src/components/Settings.js, packages/devtools-launchpad/src/components/Sidebar.js, packages/devtools-launchpad/src/components/Tabs.css, packages/devtools-launchpad/src/components/Tabs.js, packages/devtools-launchpad/src/reducers/config.js, packages/devtools-launchpad/src/selectors.js
Associate Issue: #142
The settings pane is now a component on its own.
All updates to all the existing settings (Configurations & Features) 
now use redux, and update`local.json`
@jasonLaster @jbhoosreddy
=> Settings component

packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/yarn.lock
Fixes issue with the `setValue` function import in the development server and update a lock file.
=> Fix issue with setValue import in development server

packages/devtools-client-adapters/src/chrome.js, packages/devtools-config/src/feature.js, packages/devtools-launchpad/bin/development-server.js, packages/devtools-launchpad/src/actions/config.js, packages/devtools-launchpad/src/components/Root.js, packages/devtools-launchpad/src/index.js, packages/devtools-launchpad/src/lib/themes/dark-theme.css, packages/devtools-launchpad/src/lib/themes/firebug-theme.css, packages/devtools-launchpad/src/lib/themes/light-theme.css
This gets us close to auto updating settings
Still need to work out the details
* **themes** load all of them and make sure they're scoped and we can change some classes
* **dir** flip it
* **features** flip the values and make sure that we get them loaded before we do anything else on reload...
=> (WIP) auto-update

packages/devtools-modules/client/shared/shim/Services.js
Looks like we're not stripping the prefixes
=> Fix storage bug

packages/devtools-client-adapters/index.js, packages/devtools-client-adapters/src/chrome/types.js, packages/devtools-client-adapters/src/firefox/types.js, packages/devtools-client-adapters/src/types.js, packages/devtools-client-adapters/yarn.lock
Created ChromeClientConnection type
Updated TabTarget definition
Created FirefoxClientConnection type
Created TargetEnvironments type
Created ConnectionTarget type
Stubbed out Actions type as Object for now
Created Connection type which is the union of the FirefoxClientConnection and ChromeClientConnection types
=> Flow type client moar

packages/devtools-client-adapters/src/firefox/commands.js
This addresses the caching mentioned here:
https://github.com/devtools-html/debugger.html/issues/2009
=> Remove object cache

package.json, packages/devtools-client-adapters/src/firefox.js, packages/devtools-launchpad/bin/firefox-proxy, packages/devtools-launchpad/index.js, packages/devtools-launchpad/src/development-server.js, packages/devtools-launchpad/src/index.js, packages/devtools-launchpad/src/main.js, packages/devtools-launchpad/src/server/launch.js, packages/devtools-launchpad/src/server/utils/firefox.js, packages/devtools-sham-modules/sham/chrome.js, yarn.lock
This fixes two issues connecting to firefox:
1.  refreshing several times https://github.com/devtools-html/devtools-core/issues/199
2. re-opening firefox
We also do some cleanup
1. add react 15.3.2 to core so that the launchpad can be launched by itself
2. add a simple connected component to the launchpad to test the connection
3. refactor the dev-server so that it is in src and can be modularized and linted. We'll likely want to move some src code for launchpad into a `client` dir
=> Fix some issues connecting to firefox

packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
this gives us the ability to do RTL styling with multiple rules
=> Bidirection bump

packages/devtools-launchpad/src/index.js
Fixes: https://github.com/devtools-html/debugger.html/issues/2131
=> add theme-body

packages/devtools-client-adapters/src/types.js
This addition is needed to pass flow in https://github.com/devtools-html/debugger.html/pull/2318.
=> Add sourceUrl to type Location

packages/devtools-launchpad/webpack.config.js
`devtools-source-map` is a new package using syntax that needs Babel translation, so we need to update the exclusion filter in launchpad to allow it.
=> Include devtools-source-map in Babel pipeline

packages/devtools-launchpad/src/components/Settings.js
=> [Launchpad] Add firebug menu item in settings panel

package.json, packages/devtools-launchpad/src/server/launch.js
Associate issue #214
set the correct path to `chrome-driver.js`
=> Launch chrome error

packages/devtools-launchpad/src/components/Settings.js
Commented off the switch for hot reloading
=> Temporarily disable hotReloading. Fixes issue #242

packages/devtools-client-adapters/src/chrome/commands.js
=> fix chrome pause of exceptions errors

packages/devtools-launchpad/webpack.config.js
=> update path exclude list for windows

packages/devtools-source-map/package.json, packages/devtools-source-map/src/index.js, packages/devtools-source-map/src/util.js, packages/devtools-source-map/yarn.lock
* stop passing using devtools-config and instead pass it in
* explicitly start the worker 
* start using worker-utils
this is blocked on adding worker utils and bumping the dependency
=> (WIP) Update source map worker

packages/devtools-client-adapters/src/chrome.js, packages/devtools-launchpad/configs/development.json, packages/devtools-launchpad/src/index.js
Associate issue: #257
* Switch `connectClient` and `connectNodeClient` to use async await.
* Load chrome tabs and node tabs.
=> Show chrome tabs

packages/devtools-launchpad/src/utils/L10N.js
Netmonitor.html needs this.
Copy from https://searchfox.org/mozilla-central/source/devtools/shared/l10n.js#133
=> Support numberWithDecimals in L10N

packages/devtools-client-adapters/src/chrome.js
addresses #276 
CC @rickychien
=> Catch network request errors

README.md, packages/devtools-client-adapters/README.md, packages/devtools-config/README.md, packages/devtools-launchpad/README.md, packages/devtools-modules/README.md, packages/devtools-modules/index.js, packages/devtools-network-request/README.md, packages/devtools-sham-modules/README.md, packages/devtools-source-map/README.md
Link all modules current npm badge at readme to easy checking the dependencies
demo https://github.com/gasolin/devtools-core/tree/badges
also fix #264
=> add npm badges for all modules

packages/devtools-source-map/package.json
Bug to land update in m-c: https://bugzilla.mozilla.org/show_bug.cgi?id=1351537
=> Release: Bump devtools-source-map to v0.3.0

packages/devtools-launchpad/src/index.js, packages/devtools-modules/client/shared/curl.js, packages/devtools-modules/client/shared/file-saver.js, packages/devtools-modules/index.js, packages/devtools-modules/shared/clipboard.js, packages/devtools-modules/shared/plural-form.js
* PluralForm --> devtools-modules
* curl --> devtools-modules
* file-saver --> devtools-modules
* clipboard --> devtools-modules
The PluralForm now only support English-like plural only. Need better L10N support to pass different plural local once we need to deal with the L10N
=> Bundle missed devtools-modules for netmonitor

packages/devtools-launchpad/src/lib/themes/toolbars.css
Sync toolbars.css from m-c and get rid of url.
=> Update outdated toolbars.css from m-c

packages/devtools-splitter/src/SplitBox.js, packages/devtools-splitter/stories/index.css, packages/devtools-splitter/stories/index.js
https://github.com/devtools-html/devtools-core/pull/309
=> Land  splitter onResizeEnd

packages/devtools-splitter/stories/index.css, packages/devtools-splitter/stories/index.js
=> add vertical splitter story

packages/devtools-source-editor/README.md, packages/devtools-source-editor/bin/dev-server.js, packages/devtools-source-editor/examples/index.html, packages/devtools-source-editor/examples/index.js, packages/devtools-source-editor/package.json, packages/devtools-source-editor/yarn.lock
Added a simple way to work on the source editor
=> Add Source Editor Example

packages/devtools-source-editor/src/source-editor.css
Issue: https://github.com/devtools-html/debugger.html/issues/2588
=> Atom-like style of foldgutter

packages/devtools-launchpad/src/components/shared/menu.css, packages/devtools-launchpad/src/components/shared/menu.js, packages/devtools-modules/client/framework/menu.js, packages/devtools-modules/client/shared/curl.js
Mouse hover to show sub menu in contextmenu.
and checkbox
@jasonLaster @janodvarko  @nt1m 😉
=> Support submenu for contextmenu and checkbox

packages/devtools-launchpad/src/components/shared/menu.js, packages/devtools-modules/shared/l10n.js
@gasolin Could you help me review this? This relates to https://bugzilla.mozilla.org/show_bug.cgi?id=1355833
=> Match contextmenu onClick handler to the right menu item

packages/devtools-launchpad/src/components/shared/menu.js
=> [launchpad] fix menus #334

packages/devtools-connection/src/target.js, packages/devtools-connection/src/transport/packets.js, packages/devtools-connection/src/utils/events.js, packages/devtools-connection/src/webconsole/client.js, packages/devtools-modules/src/utils/event-emitter.js
some of the code got prettified in the move, which would make it difficult to track changes
=> Un prettify source code

packages/devtools-launchpad/.storybook/webpack.config.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
This restores launchpad's storybook instance to its former glory:
=> Fix storybook

packages/devtools-source-editor/examples/index.css, packages/devtools-source-editor/examples/index.html, packages/devtools-source-editor/examples/index.js, packages/devtools-source-editor/package.json, packages/devtools-source-editor/src/source-editor.css
* updates the debug line
* adds additional styling for the editor
=> Style dbg line

packages/devtools-source-editor/src/source-editor.css
Removes the highlighting css from source-editor
=> Remove the highlight css

packages/devtools-source-map/package.json, packages/devtools-source-map/src/source-map.js, packages/devtools-source-map/src/tests/fixtures/empty.js, packages/devtools-source-map/src/tests/fixtures/empty.js.map, packages/devtools-source-map/src/tests/source-map.js
This isn't the last time we'll have to work on source map URL resolution, but it fixes up something I introduced yesterday and lets us make a bit of progress.
=> Source map url resolution

packages/devtools-launchpad/src/lib/themes/variables.css
This is to be future used with https://github.com/devtools-html/debugger.html/pull/3022
=> new yellow highlight added to theme variables (#385)

packages/devtools-license-check/bin/devtools-license-check, packages/devtools-license-check/package.json
This updates the list of licenses and waivers based on investigation of
some failures in https://github.com/devtools-html/devtools-core/pull/388
=> Update list of licenses and waivers

bin/install-yarn, circle.yml, package.json, packages/devtools-launchpad/bin/chrome-driver.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock, yarn.lock
This is @zaggy 's fix. I'm refiling because git got weird
=> fix chrome driver

packages/devtools-connection/src/debugger/client.js, packages/devtools-launchpad/src/client/firefox.js
this adds the client support for getting frame environments.
=> Add getEnvironment

packages/devtools-modules/src/menu/index.js
This updates the menuitem dom to accomodate windows CSS styling
https://github.com/devtools-html/debugger.html/issues/1942
=> Fix menuitem padding

circle.yml, packages/devtools-reps/package.json, packages/devtools-reps/yarn.lock
=> Update node and jest version

packages/devtools-launchpad/src/client/chrome.js
Doing this because there are currently issues #410
=> disable chrome

packages/devtools-launchpad/src/client/chrome.js, packages/devtools-launchpad/webpack.config.js
Fixes #410
Thanks to @cyrus-and
=> fix for the cri bug

packages/devtools-launchpad/src/index.js
=> reconnect to firefox client again to get tab updates

packages/devtools-reps/package.json, packages/devtools-reps/src/launchpad/actions/expressions.js, packages/devtools-reps/src/launchpad/components/Console.css, packages/devtools-reps/src/launchpad/components/Console.js, packages/devtools-reps/src/launchpad/index.js, packages/devtools-reps/yarn.lock
Because of this, the Reps test app needed to be modified in
order to work properly.
I took this as an opportunity to clean out some warnings too.
=> Bump-up launchpad for devtools-reps

packages/devtools-launchpad/src/client/chrome.js, packages/devtools-reps/package.json
This error was showing up on prepush
=> Fix eslint error

flow-typed/debugger-html.js, packages/devtools-connection/src/debugger/client.js, packages/devtools-source-map/src/source-map.js, packages/devtools-source-map/src/tests/wasm-source-map.js, packages/devtools-source-map/src/wasm-source-map.js
Continuation of https://bugzilla.mozilla.org/show_bug.cgi?id=1364535 but for debugger.html.
=> Support of the WebAssembly source maps and binary sources

packages/devtools-reps/src/object-inspector/index.js
This is a simple change.
it does not have test, but I'm planning to tackle this as https://github.com/devtools-html/devtools-core/issues/472 .
=> Renders non-root nodes in a lesser  mode than the root node.

packages/devtools-source-map/src/tests/source-map.js
hasMappedSource should check the string contents
=> Fix equality check

packages/devtools-reps/src/reps/object-with-url.js, packages/devtools-reps/src/reps/tests/object-with-url.js
The getTitle function wasn't called with the expected arguments.
=> Fix ObjectWithURL rendering.

packages/devtools-contextmenu/menu.js
Fix top position of context sub-menu (issue #471)
Honza
=> Issue 471 - fix position of context sub-menu

packages/devtools-reps/package.json
Let's wait until https://bugzilla.mozilla.org/show_bug.cgi?id=1308566 lands in mozilla-central
=> Release: bump version to v0.9

packages/devtools-connection/package.json, packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock, packages/devtools-source-map/package.json, packages/devtools-source-map/yarn.lock, packages/devtools-utils/package.json
It would be nice to bump these packages so that we can pull the latest changes into the debugger.
=> Bump devtools connection + source-map

packages/devtools-reps/.flowconfig, packages/devtools-reps/src/object-inspector/index.js, packages/devtools-reps/src/object-inspector/tests/utils/__snapshots__/promises.js.snap, packages/devtools-reps/src/object-inspector/tests/utils/create-node.js, packages/devtools-reps/src/object-inspector/tests/utils/get-children.js, packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-properties.js, packages/devtools-reps/src/object-inspector/tests/utils/node-supports-bucketing.js, packages/devtools-reps/src/object-inspector/tests/utils/promises.js, packages/devtools-reps/src/object-inspector/types.js, packages/devtools-reps/src/object-inspector/utils.js
Flow type
Refactor/Renaming to be more consistent
Add some tests
=> ObjectInspector util functions

packages/devtools-launchpad/package.json, packages/devtools-launchpad/postcss.config.js, packages/devtools-launchpad/webpack.config.js, packages/devtools-reps/package.json
=> Fix Reps Launchpad

packages/devtools-reps/src/launchpad/index.js, packages/devtools-reps/yarn.lock
Removing it since it's not used at the moment. This will be taken care of as part of #395.
=> Remove l10n from Reps launchpad.

packages/devtools-reps/package.json
Here's the review for the new bundle https://reviewboard.mozilla.org/r/166018/
=> [WIP] Release: bump devtools-reps version to v0.12.0

packages/devtools-modules/index.js, packages/devtools-modules/src/zoom-keys.js
Related to bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1388368
Honza
=> Bug1388368

packages/devtools-components/package.json
Bump the package version so we can use changes made in
https://github.com/devtools-html/devtools-core/commit/9a30b5faf2e3ac4882cfac6bc6053134aca05e65\#diff-d28797e041808f39b6f7d1b93afcc46a.
=> Bump devtools-components version to 0.0.2.

packages/devtools-launchpad/src/tools/mc/make-bundle.js, packages/devtools-reps/bin/copy-assets.js
the most annoying thing about mochitests is that they update the assets file. this makes that configurable now
=> ignore assets

packages/devtools-launchpad/package.json
=> bump devtools-launchpad from 0.0.90 to 0.0.92

packages/devtools-reps/package.json
0.12.1 bundle landed in m-c (https://hg.mozilla.org/mozilla-central/rev/87afcda8a0ff). We can push the new version.
=> Reps 0.12.1

packages/devtools-source-map/package.json, packages/devtools-source-map/yarn.lock
Also require devtools-core 0.0.7
=> Release: Bump devtools-source-map to 0.11.0

packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
Uses a newest version of devtools-connection
=> Bump up devtools-launchpad.

packages/devtools-launchpad/package.json
Added the assets folder to package.json to be included in the build
=> added assets directory to files property in package.json

packages/devtools-launchpad/src/components/Sidebar.js, packages/devtools-launchpad/src/tools/tests/webpack.config.js
Fix babelExclude test
Fix eslint errors
=> Launchpad fixes

packages/devtools-launchpad/src/components/Sidebar.js, packages/devtools-launchpad/webpack.config.js
**Don't mix import and require.**
This was causing an error in consumer of the package (exports
is read-only).
Switching to require fixes the issue.
**Guarding options**
=> Fix launchpad errors

packages/devtools-reps/src/reps/tests/grip-map-entry.js
=> Fix grip map entry test

packages/devtools-source-map/package.json
Also require devtools-core 0.0.8
=> Release: Bump devtools-source-map to 0.12.0

packages/devtools-config/package.json, packages/devtools-config/src/feature.js, packages/devtools-config/tests/feature.js, packages/devtools-config/yarn.lock, packages/devtools-launchpad/webpack.config.devtools.js, packages/devtools-reps/src/object-inspector/utils.js
We vendored lodash in the last release. This means that we can safely count on it being available on the m-c side.
=> Clean lodash

packages/devtools-launchpad/package.json
=> move svg-inline-loader

packages/devtools-components/package.json
Associated Issue: #<issue number>
* change 1
* change 2
Tell us a little a bit about how you tested your patch.
=> Bump-up devtools-components to 0.0.3

packages/devtools-license-check/bin/devtools-license-check, packages/devtools-license-check/package.json
bump license checker to include a dev dependency
=> whitelist ini-parser

packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
eslint-plugin-mozilla the older version was breaking w/ our estree upgrades w/ other packages
=> Bump eslint-plugin-mozilla

circle.yml, flow-typed/debugger-html.js, packages/devtools-map-bindings/.babelrc, packages/devtools-map-bindings/package.json, packages/devtools-map-bindings/src/scopes.js, packages/devtools-map-bindings/src/tests/scopes.js, packages/devtools-source-map/src/index.js, packages/devtools-source-map/src/source-map.js, packages/devtools-source-map/src/worker.js
Associated Issue: https://github.com/devtools-html/debugger.html/issues/3427
* merges parsed scopes in generated source with names information from source maps
See https://github.com/devtools-html/debugger.html/pull/3817
=> AST scopes/binding to names mapping.

circle.yml, package.json, packages/devtools-components/.babelrc, packages/devtools-components/package.json, packages/devtools-components/src/tests/__mocks__/request-animation-frame.js, packages/devtools-components/src/tests/__mocks__/styleMock.js, packages/devtools-components/src/tests/__mocks__/svgMock.js, packages/devtools-components/src/tests/__snapshots__/tree.js.snap, packages/devtools-components/src/tests/tree.js, packages/devtools-components/src/tree.js, packages/devtools-components/stories/tree.js, packages/devtools-components/yarn.lock
Sync the Tree component with m-c
Add a story for focused node
Add tests for the Tree component (this migrates the `test_tree_*` tests of http://searchfox.org/mozilla-central/source/devtools/client/shared/components/test/mochitest/ to jest).
=> Component tests

flow-typed/debugger-html.js, packages/devtools-map-bindings/package.json, packages/devtools-map-bindings/src/parser.js, packages/devtools-map-bindings/src/tests/__snapshots__/parser.js.snap, packages/devtools-map-bindings/src/tests/fixtures/es5.js, packages/devtools-map-bindings/src/tests/fixtures/es6.js, packages/devtools-map-bindings/src/tests/helpers/index.js, packages/devtools-map-bindings/src/tests/parser.js
Associated Issue: #624
* Extracts code from https://github.com/devtools-html/debugger.html/pull/3852
* Adds babel-traverse for testing
=> Implements getScope parsing in the devtools-map-bindings

packages/devtools-source-map/src/source-map.js, packages/devtools-source-map/src/tests/getContentType.js, packages/devtools-source-map/src/tests/isURL.js, packages/devtools-source-map/src/tests/source-map.js
Some small code health wins
* fixed some of the tests, which were missing a `describe` and weren't running
* run the code through prettier
=> Source Maps Code improvements

packages/devtools-components/package.json
=> Bump up devtools-components to 0.0.5

packages/devtools-reps/package.json, packages/devtools-reps/webpack.config.js
Following [RELEASE.md](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-reps/RELEASE.md).
=> Bump up devtools-reps to 0.14.0.

packages/devtools-launchpad/src/index.js
=> Pass custom properties to root App component

packages/devtools-source-map/package.json, packages/devtools-source-map/yarn.lock
bumping the source maps lib to include an up to date version of mappings
=> Bump source maps

packages/devtools-components/stories/tree.js
Huge tree so we can sort out performances
=> Add a 30,000 items tree story

packages/devtools-reps/src/reps/document.js, packages/devtools-reps/src/reps/stubs/document.js, packages/devtools-reps/src/reps/tests/document.js
=> Handle location-less document grips

packages/devtools-components/src/tree.css
Associated Issue: #3789
Removes cursor pointer from tree for more cursor consistency
visual test on clicking tree
=> Remove cursor: pointer from tree

lerna.json, package.json, packages/devtools-components/package.json, packages/devtools-contextmenu/package.json, packages/devtools-launchpad/bin/validate-deps.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock, packages/devtools-license-check/package.json, packages/devtools-map-bindings/package.json, packages/devtools-modules/package.json, packages/devtools-reps/package.json, packages/devtools-source-map/package.json, packages/devtools-splitter/package.json, yarn.lock
...
P.S. [lerna][l] is amazing. Lets try to use it exclusively for publishing. This update was huge, but it should do the smallest subset of releases possible
[l]:https://lernajs.io/
=> sync follow up + published packages

packages/devtools-reps/src/object-inspector/index.js, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/basic.js.snap, packages/devtools-reps/src/object-inspector/tests/component/basic.js, packages/devtools-reps/yarn.lock
Fix #756
~Need a test~  test added
=> Update ObjectInspector when root property changes

.gitignore, packages/devtools-launchpad/.babelrc, packages/devtools-launchpad/assets/Svg.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/webpack.config.js, packages/devtools-launchpad/yarn.lock
=> cleanup babel

packages/devtools-map-bindings/src/tests/utils.js, packages/devtools-map-bindings/src/utils.js
Associated Issue: #741 
* `mapIdentifiers` parses an expression via AST and maps identifiers to their minified values
* wrote some assertions to test behavior of the `mapIdentifiers` function
=> map identifiers to names

packages/devtools-launchpad/package.json
Update to the latest version to get this PR:
https://github.com/song940/kelp-static/pull/1
Honza
=> Update to latest version of express-static

README.md, circle.yml, package.json, packages/devtools-connection/package.json, packages/devtools-contextmenu/package.json, packages/devtools-launchpad/yarn.lock, packages/devtools-license-check/package.json, packages/devtools-reps/yarn.lock, packages/devtools-source-editor/package.json, packages/devtools-splitter/package.json, packages/devtools-styleguide/package.json
Associated Issue: #773
* Provided a way to test all packages using a single command
=> Provide a way to test all packages using a single command #773

flow-typed/debugger-html.js, packages/devtools-map-bindings/src/remapScopes.js, packages/devtools-map-bindings/src/tests/__snapshots__/remapScopes.js.snap, packages/devtools-map-bindings/src/tests/__snapshots__/updateScopeBindings.js.snap, packages/devtools-map-bindings/src/tests/remapScopes.js, packages/devtools-map-bindings/src/tests/updateScopeBindings.js, packages/devtools-map-bindings/src/updateScopeBindings.js
Associated Issue: https://github.com/devtools-html/debugger.html/pull/4521
* Adds remapScopes utility function to the devtools-map-bindings package.
=> Adds remapScopes utility function.

packages/devtools-map-bindings/package.json, packages/devtools-map-bindings/src/scopes.js, packages/devtools-source-map/package.json
Associated Issue: https://github.com/devtools-html/debugger.html/pull/4521#issuecomment-343340338
=> Records non-modified names in the scopes.

packages/devtools-map-bindings/package.json, packages/devtools-map-bindings/src/scopes.js, packages/devtools-map-bindings/src/tests/scopes.js, packages/devtools-source-map/package.json
Associated Issue: https://github.com/devtools-html/debugger.html/pull/4521#issuecomment-343592062
* Identify names mapping if names section is empty
=> Recovering empty names section.

packages/devtools-modules/src/Services.js, packages/devtools-modules/src/tests/services-telemetry.js
=> Create telemetry shims

packages/devtools-components/src/tree.js
=> Fix refs usage.

packages/devtools-reps/package.json, packages/devtools-reps/webpack.config.js
Let's create a bundle and push it to TRY to see if everything is fine.
=> Release: bump up devtools-reps to 0.15.0

packages/devtools-components/package.json, packages/devtools-components/src/tree.css
Fix non-expandable node alignment.
=> Bump devtools-components to 0.1.1.

packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/getter-setter.js.snap, packages/devtools-reps/src/reps/function.js, packages/devtools-reps/src/reps/tests/function.js
Underlying logic borrowed from the debugger
=> Simplify function

packages/devtools-reps/package.json, packages/devtools-reps/src/object-inspector/index.css, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap, packages/devtools-reps/src/object-inspector/tests/test-utils.js, packages/devtools-reps/yarn.lock
Update devtools-components version in devtools-reps
---
Waiting for devtools-components-0.1.1 to be published
=> Update reps devtools components

packages/devtools-reps/src/reps/object.js
The patch minimizes the amount of time we have to build the keys
from an object and loop over it.
=> More efficient Object Reps construction.

packages/devtools-reps/src/reps/rep-utils.js, packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/tests/string-with-url.js
=> Fix linkification for cropped URLs

packages/devtools-launchpad/src/main.js
Associated Issue: #839 
* added .catch to handle promise rejection 
* style changes introduced automatically by prettier-atom code formatter
=> Adds error handling for onConnect rejection

packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/stubs/error.js, packages/devtools-reps/src/reps/tests/error.js
=> Add handling for a DOMException error; Fixes #682

packages/devtools-connection/package.json
r=me for updating package version
=> Release devtools-connection-0.0.8

packages/devtools-launchpad/package.json
Update devtools-connection to 0.0.8 and bump up devtools-launchpad to 0.0.113
=> Update devtools-connection to 0.0.8

packages/devtools-reps/src/reps/grip-array.js, packages/devtools-reps/src/reps/stubs/grip-array.js, packages/devtools-reps/src/reps/tests/grip-array.js, packages/devtools-reps/src/reps/tests/grip.js
=> Modify GripArray to show some ArrayLike objects in Tiny mode.

packages/devtools-reps/src/reps/object-with-text.js, packages/devtools-reps/src/reps/stubs/object-with-text.js, packages/devtools-reps/src/reps/tests/object-with-text.js, packages/devtools-reps/src/reps/tests/object.js
Associated Issue: #684
Implement CSSRule reps for showing CSSStyleRule node.
=> Modify ObjectWithText to show the class of the object

packages/devtools-modules/package.json
=> Release devtools-modules-0.0.34

packages/devtools-components/postcss.config.js
This prevent the launchpad from throwing
=> Add dummy postCSS config file

packages/devtools-reps/src/reps/function.js, packages/devtools-reps/src/reps/stubs/function.js, packages/devtools-reps/src/reps/tests/function.js
=> Do not add jump to definition icon for evaled in debugger functions.

packages/devtools-reps/package.json
~~Waiting for [review](https://reviewboard.mozilla.org/r/208804/)~~
[TRY run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=b7b49623935f1c5f6ff9154d74162edf0bf9c0e0) : ✅
Waiting for the patch to be merged to mozilla-central
=> [WIP] Release: bump version to devtools-reps-0.17.0

packages/devtools-reps/src/object-inspector/tests/component/function.js, packages/devtools-reps/src/reps/function.js, packages/devtools-reps/src/reps/stubs/function.js, packages/devtools-reps/src/reps/tests/function.js
This is a modified version of https://github.com/devtools-html/devtools-core/pull/771 green tests
=> Duplicate scopes

packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/tests/string-with-url.js
=> Fix string with URL rendering when cropping not needed

packages/devtools-license-check/package.json
=> Bump devtools-license-check to 0.6.0

packages/devtools-components/package.json
=> Bump devtools-components to 0.1.4

packages/devtools-reps/src/reps/stubs/grip.js, packages/devtools-reps/src/reps/tests/grip.js
=> Add a Rep test for Generators

packages/devtools-reps/package.json
[Bug 1430547](https://bugzilla.mozilla.org/show_bug.cgi?id=1430547)
=> Bump devtools-reps to 0.19.0

packages/devtools-reps/package.json
=> [WIP] Bump devtools-reps to 0.19.1

packages/devtools-components/src/tree.css
Associated Issue: #912 
* Change hover color to --theme-selection-background-hover
* Make any images the same color as the arrow when hovered.
=> Fix colors

packages/devtools-map-bindings/package.json, packages/devtools-map-bindings/yarn.lock, packages/devtools-source-map/package.json, packages/devtools-source-map/yarn.lock, packages/devtools-utils/package.json
This bumps devtools-utils and the dependent packages.
=> Bump devtools utils

packages/devtools-reps/src/reps/stubs/element-node.js, packages/devtools-reps/src/reps/tests/element-node.js
=> Add a test for Element with longString attribute.

packages/devtools-reps/src/reps/object.js, packages/devtools-reps/src/reps/tests/object.js
=> Do not check object.class to get the title ithe Object rep.

packages/devtools-components/package.json, packages/devtools-reps/package.json, packages/devtools-reps/yarn.lock
Pulls in the latest tree styling
=> Update devtools reps

packages/devtools-reps/src/reps/accessor.js, packages/devtools-reps/src/reps/array.js, packages/devtools-reps/src/reps/document.js, packages/devtools-reps/src/reps/grip-array.js, packages/devtools-reps/src/reps/grip-map-entry.js, packages/devtools-reps/src/reps/grip-map.js, packages/devtools-reps/src/reps/grip.js, packages/devtools-reps/src/reps/object-with-text.js, packages/devtools-reps/src/reps/prop-rep.js, packages/devtools-reps/src/reps/rep-utils.js, packages/devtools-reps/src/reps/window.js
I initiated this work in order to find areas where we could use fragments, but it seems like we are already careful on what we create.
There were only a few places where I was able to remove unnecessary nodes.
I took this as an opportunity to clean up the code a bit.
=> Reps code cleanup

packages/devtools-reps/src/launchpad/components/Console.css, packages/devtools-reps/src/launchpad/samples.js, packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/reps.css, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap, packages/devtools-reps/src/reps/tests/error.js
=> Add prettier formatting for error rep's stacks

packages/devtools-components/package.json, packages/devtools-components/src/tests/setup.js, packages/devtools-components/src/tests/tree.js, packages/devtools-components/yarn.lock
Needed a new version of Enzyme and some minor changes in tests.
=> Update devtools-components to React 16.

.flowconfig, packages/devtools-launchpad/.babelrc, packages/devtools-launchpad/.storybook/config.js, packages/devtools-launchpad/bin/firefox-proxy, packages/devtools-launchpad/package.json, packages/devtools-launchpad/stories/index.js, packages/devtools-launchpad/yarn.lock
Tests and storybook runs fine (even if I had to comment loading the css file)
=> Use React 16 in devtools-launchpad

packages/devtools-reps/configs/development.json, packages/devtools-reps/package.json, packages/devtools-reps/src/object-inspector/tests/component/classnames.js, packages/devtools-reps/src/object-inspector/tests/component/expand.js, packages/devtools-reps/src/object-inspector/tests/test-utils.js, packages/devtools-reps/src/reps/tests/__snapshots__/element-node.js.snap, packages/devtools-reps/src/reps/tests/__snapshots__/nan.js.snap, packages/devtools-reps/src/reps/tests/element-node.js, packages/devtools-reps/src/reps/tests/event.js, packages/devtools-reps/src/test/setup.js, packages/devtools-reps/yarn.lock
Update devtools-* packages as well.
=> Update devtools-reps to React 16.2.

packages/devtools-license-check/bin/devtools-license-check
These changes are needed for some dependency upgrades in the debugger.html
https://github.com/devtools-html/debugger.html/issues/5560
https://github.com/devtools-html/debugger.html/issues/5465
I included a prettier commit, but the 2nd commit has the relevant changes.
https://creativecommons.org/publicdomain/zero/1.0/
https://en.wikipedia.org/wiki/BSD_licenses
=> License improvements

packages/devtools-reps/package.json, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/properties.js.snap, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/window.js.snap, packages/devtools-reps/src/object-inspector/tests/component/classnames.js, packages/devtools-reps/src/object-inspector/tests/component/properties.js, packages/devtools-reps/src/object-inspector/tests/component/window.js, packages/devtools-reps/src/reps/tests/__snapshots__/element-node.js.snap, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap, packages/devtools-reps/src/reps/tests/__snapshots__/nan.js.snap, packages/devtools-reps/src/reps/tests/element-node.js, packages/devtools-reps/src/reps/tests/error.js, packages/devtools-reps/src/test/setup-file.js, packages/devtools-reps/yarn.lock
Fixes #943.
Updates a few test to use plain Enzyme wrapper. or better, custom formatObjectInspector helper.
Updates snapshots.
=> Add enzyme-to-json serializer.

packages/devtools-reps/src/reps/function.js
This way we can expose it for other part of the code to use it.
=> Create a cleanFunctionName function extracted from getFunctionName.

packages/devtools-components/src/tests/tree.js, packages/devtools-components/src/tree.css, packages/devtools-components/src/tree.js
(according to spec values should be >= 1).
Fixes #963.
=> Tree's aria-level should be depth + 1

packages/devtools-reps/src/object-inspector/component.js, packages/devtools-reps/src/object-inspector/index.css, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/basic.js.snap, packages/devtools-reps/src/object-inspector/tests/component/basic.js, packages/devtools-reps/src/object-inspector/tests/test-utils.js, packages/devtools-reps/src/object-inspector/utils/node.js
Fixes #940.
Visual is still discussed at https://github.com/devtools-html/debugger.html/issues/5426#issuecomment-366620776 and might change.
=> Add a new BLOCK node type in the ObjectInspector.

packages/devtools-components/package.json
=> Bump devtools-components to 0.3.0

packages/devtools-reps/src/object-inspector/component.js, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/expand.js.snap, packages/devtools-reps/src/object-inspector/tests/component/expand.js
It was causing an issue in the debugger with scopes "Block" nodes
=> Guard isRoot on node value truthiness

packages/devtools-reps/src/object-inspector/utils/load-properties.js
This was moved to a redux action
=> Delete unused loadItemProperties function.

packages/devtools-reps/.babelrc, packages/devtools-reps/package.json, packages/devtools-reps/postcss.config.js, packages/devtools-reps/webpack.config.js, packages/devtools-reps/yarn.lock
+ adjust webpack and babel config
=> Add plugins to not transpile spread operator

packages/devtools-components/package.json, packages/devtools-components/src/images/arrow.svg, packages/devtools-components/src/tests/__mocks__/svgMock.js, packages/devtools-components/src/tests/tree.js, packages/devtools-components/src/tree.css, packages/devtools-components/src/tree.js, packages/devtools-components/webpack.config.js, packages/devtools-components/yarn.lock
Inspired by the work on the debugger.
The storybook command was modified so images are served as expected.
The xmlns attribute was restored since it is needed for the image to be displayed
Removed now unnecessary InlineSvg dependency.
=> Don't use inline SVG for the arrow in Tree component.

packages/devtools-components/package.json, packages/devtools-components/postcss.config.js, packages/devtools-components/src/tree.css
Set a proper postCSS config to manage images in different environments (sotrybook, reps-launchpad, mozilla-central)
Bump to 0.4.1
=> devtools-components postCSS config

packages/devtools-reps/package.json
WIP because we follow the release process
=> [WIP] Release: devtools-reps 0.21.0

packages/devtools-reps/package.json
=> Update devtools-reps to 0.21.1

packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/reps.css, packages/devtools-reps/src/reps/tests/error.js
=> Use onViewSourceInDebugger prop when clicking on the Error rep stacktrace location

packages/devtools-reps/src/reps/element-node.js, packages/devtools-reps/src/reps/stubs/element-node.js, packages/devtools-reps/src/reps/tests/element-node.js
* Label content of pseudo element to "::before" or "::after".
Please use `yarn test`
=> Bug 1450526 - Part 3: Changing label content of pseudo element

packages/devtools-reps/src/reps/element-node.js, packages/devtools-reps/src/reps/tests/element-node.js
* Extend ElementNode to change the title of inspect icon from outside
* Extend ElementNode to add clicking listener
For https://bugzilla.mozilla.org/show_bug.cgi?id=1453010
Please run `yarn test`
=> For bug 1453010

packages/devtools-components/src/tests/__snapshots__/tree.js.snap, packages/devtools-components/src/tests/tree.js
This way tree nodes in snapshot are well aligned.
=> Wrap text representation of Tree in new lines.

.flowconfig
=> Ignore babel-plugin-react-docgen in flow

packages/devtools-launchpad/bin/chrome-driver.js, packages/devtools-launchpad/bin/firefox-driver.js, packages/devtools-launchpad/bin/validate-deps.js
run prettier on devtools-launchpad/bin/*.js
=> run prettier on devtools-launchpad/bin/*.js

packages/devtools-services/package.json
Version 0.0.1 was pushed to npm with some errors.
=> Bump devtools-services to 0.0.2.

packages/devtools-launchpad/package.json, packages/devtools-launchpad/src/components/Root.css
backporting Bug 1471162 - Style codemirror scrollbar corners correctly in dark-theme;r=gl
=> [launchpad] scroller

packages/devtools-connection/package.json, packages/devtools-connection/src/debugger/client.js, packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
=> update RootClient getFront endpoint

.flowconfig, packages/devtools-connection/src/debugger/client.js
* Add methods to set and remove xhr breakpoints
=> add methods to debugger client for xhr breakpoints

packages/devtools-connection/src/debugger/client.js
Replicate API from https://bugzilla.mozilla.org/show_bug.cgi?id=1515438
=> Add API query fns for breakpoint locations.

packages/devtools-launchpad/src/components/LandingPage.js
Associated Issue: #<issue number>
* Fix image path prefix. Tested with `debugger.html`
=> Fix image path prefix

packages/devtools-launchpad/src/index.js
Associated Issue: #1095
When Launchpad theme is switched only the one theme class (`theme-dark`, `theme-light`, ...) is switched on the `root` and `appRoot` elements.
This way we don't replace the whole class string and get to keep other classes that were set on the element before.
E.g. Currently `html` class disappears after the theme is switched.
https://github.com/devtools-html/devtools-core/blob/c4fa6097a69c7b5d2156070532cc5b9374713040/packages/devtools-launchpad/src/index.js#L57
Not the best solution and can be 100% improved if 😢 
1. there was a unique theme prefix (`active-theme-` or something like that) then we could just replace the class without filtering;
2. or even better `classList` wasn't manipulated directly and we had a `Theme` react component / provider.
I can take a stab …
=> Fixes launchpad theme switching logic #1095.

packages/devtools-connection/src/debugger/client.js
bug 990137, bug 1520993, and bug 1520972 made changes to the m-c/devtools/shared clients.  This PR ports these changes to the client implementation in devtools-connection.
I still need to test this patch manually.
=> Update client for changes in bug 990137, bug 1520993, bug 1520972.

packages/devtools-connection/src/debugger/client.js
APIs landing in https://bugzilla.mozilla.org/show_bug.cgi?id=1531874
=> Add client functions for new event breakpoint API.

packages/devtools-config/src/feature.js
These seemed to be missing and the associated tests were failing.
Returning booleans.
=> add isDevelopment and isEnabled to feature.js

packages/devtools-modules/index.js, packages/devtools-modules/src/async-store-helper.js
Adds asyncStoreHelper to shared space for Debugger and Inspector
See also: https://phabricator.services.mozilla.com/D38534
=> Add asyncStoreHelper to devtools-modules

packages/devtools-modules/index.js, packages/devtools-modules/package.json
=> Fix typo and bimp devtools-module to 1.1.9

packages/devtools-contextmenu/package.json
require the newest version of devtools-modules
=> Bump devtools-contextmenu to 1.0.14.

packages/devtools-launchpad/package.json, packages/devtools-launchpad/yarn.lock
updates the launchpad to have a more minimal mc-assets
=> bump launchpad
